### ISSUE TITLE
Enhancement: Provide timestamp to Start and End of test file in EP_CLI log

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#10]
The only start and stop timestamps can be found in the Reports.  We would like to see a time stamp reported in the EP_CLI log when a test file starts and ends.

**Comment by bogdanpopescu** [comment]
Timestamp for start and end of execution implemented. Added as well the elapsed time. 
@CJHoffmann  please check in tag 31_05_2013

**Comment by sandhyamisra** [comment]
1. Currently,  Once the test script completes execution a line as below is printed in the log file towards the end of test case log.
   
   ```
           "Test statistics: Start time 2013-06-03 09:42:38 -- End time 2013-06-03 09:42:38 -- 0.06 sec."
   ```

Expected: We need time stamp for each line being executed similar to the logs present in /opt/twister/logs. Below is the sample for the same.
        <..
        13-06-03 10:08:53  DEBUG    setStartedBy: CE: Started by user name `user`.
        13-06-03 10:08:55  DEBUG    downloadLibrary: CE: Requested library file: `/opt/twister/lib/StepLib.py`.
        13-06-03 10:08:55  DEBUG    downloadLibrary: CE: Requested library file: `/opt/twister/lib/TestBed.py`.
        13-06-03 10:08:55  DEBUG    downloadLibrary: CE: Requested library file: `/opt/twister/lib/Threads.py`.
        13-06-03 10:08:55  DEBUG    downloadLibrary: CE: Requested library file: `/opt/twister/lib/TscFtp.py`.
        13-06-03 10:08:55  DEBUG    downloadLibrary: CE: Requested library file: `/opt/twister/lib/TscTelnet.py`.
    ..>

```
2. Another issue found is when the test script crashes during execution the "Test statistics" line itself is not printed in the log
```

**Comment by bogdanpopescu** [comment]
@sandhyamisra Please be more specific when you open an issue and expect something. I don't get it what do you expect in terms of timestamp as long we provided Start,End and elapsed time. 
For the second issue, please open a separate issue in github, it is not related to timestamp request.

**Comment by sandhyamisra** [comment]
We need time stamps for each line that is printed in the log so that it is easy to locate the delays (if any) between the lines of executed code and also for other debugging purposes. 
The logs that are available in the /opt/twister/logs directory have the time stamps as we expect. A sample of the logs are provided in my previous comment.

**Comment by bogdanpopescu** [comment]
The framework can provide start and end timestamp every time a test case is started. If you need time stamp for every line, including the lines that comes from CLI interaction with the devices, it's a matter of test case. For instance, if you want a time stamp when a command is send to device and a time stamp for the reply received, you have to put that into the test case coding. Framework doesn't control that.

**Comment by sandhyamisra** [comment]
We agree with your view. This issue can be closed. Thanks
