### ISSUE TITLE
CHANGE_TESTBED role is being assigned automatically to a user if CHANGE_SUT role is assigned

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#103]
When I change the role of an user to have CHANGE_SUT role, in the Twister GUI he is allowed to modify testbeds also (hence user is getting CHANGE_TESTBED role as well).
Is this is what intended (if yes why)? please explain.

Thank you,
- Jai

**Comment by bogdanpopescu** [comment]
This is a bug that needs to be fixed.

**Comment by bogdanpopescu** [comment]
Closing, this was fixed.
