### ISSUE TITLE
Enhance Report Folders to be collapsable/expandable

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#104]
Creating folders does not do much
        <report ID="Details (Select User)" Folder="Details User" 

Would like to see them collapsible/expandable.

**Comment by croqaz** [comment]
Ok, good idea. Will work on that.
~ Cristi

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Hi, the issue was fixed in 17th January delivery, please verify it.

**Comment by mtkuntz** [comment]
Collapsing the Folder hide everything below. Collapse Details User and I cannot see Summary User
Folder="Details User"
Folder="Summary User"

Seems like you need to delimit the end of a folder

Folder="Details User"
FolderEnd="Details User"
...
...
Folder="SummaryUser"
FolderEnd="SummaryUser"

**Comment by mtkuntz** [comment]
OK to close - fixed
