### ISSUE TITLE
CE web interface control of users' client does not work.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#106]
from the CE web interface (server:8000) it appears I am stopped.

Status  stopped ( start  | stop  | reset! )

but not from the servers point-of-view.

> > > > ||||  Status twister client:

mkuntz    8229     1  0 15:24 pts/1    00:00:01 /usr/local/bin/python2.7 -u /home/mkuntz/twister/bin/start_client.py

starting, stopping, resetting DO change the status shown on the web server but the actual client is unaffected.

**Comment by croqaz** [comment]
Hello,
The CE Web Interface is not dynamic, like the applet; that means it doesn't update the statuses LIVE.
So, if you run some tests in the applet, the Web Interface will only show the status `Running` after a page refresh.
The Web Interface can start and stop the execution status almost like the applet, but you cannot create, or change the suites. So, after you make a suite in the applet, you can run that same suite using the Web Interface.
You must refresh the page from time to time, to see the status.
The role of the Web Interface is not to completely replace the applet, but to offer a very light and fast interface.
~ Cristi

**Comment by mtkuntz** [comment]
I thought it had to do with the Client status.OK to Close
