### ISSUE TITLE
CentralEngine.py is failing..Please see the log

### ISSUE THREAD

**Issue by Debal99** [Luxoft/Twister#107]
![c--users-debal basuroy-desktop-debal_temp-twister_log txt](https://f.cloud.github.com/assets/6151321/1713961/5f45d0c0-6197-11e3-9c5d-5941239a6aa5.png)

**Comment by croqaz** [comment]
Hello,
This exception happens for one reason: you didn't install the twister client on the machine with the Central Engine.
The Central Engine needs to read your user configurations, in order to create your user profile.
Please, use the Twister Guide to learn how to install the client.
~ Cristi
