### ISSUE TITLE
NeedHelp:How to create username and password to access GUI

### ISSUE THREAD

**Issue by Debal99** [Luxoft/Twister#108]
![screenshot-3](https://f.cloud.github.com/assets/6151321/1713980/d4afcff0-6197-11e3-88fa-a8ed524d0a86.png)

**Comment by baluthomas** [comment]
Login is based on linux user.
First log in using the user provided in the user and group config file.
Change the name of the first user to the linux user.

Also SSH service should be running.

**Comment by Debal99** [comment]
Could please tell me which one of the user and password from the file users_and_groups.ini ,I should use

github.com/Luxoft/Twister/blob/git_hub_branch/config/users_and_groups.ini

**Comment by croqaz** [comment]
Hello,
First, you need to install twister server.
Second, you need to install the twister client for your linux user. The installer will create a folder called "twister", in your home directory.
Then, you need to have openssh-server installed. The applet will connect on you machine using your username and password, but only if your username can be found in users_and_groups, on the Central Engine settings.
So, you need to update the users_and_groups file fron the Central Engine folder, so the Central Engine knows about your user.

All this information and MUCH MORE can be found in the user guide. It's hard to explain everything in a comment.
You should read the guide from docs folder and if you have more questions, please don't hesitate to ask.
~ Cristi
