### ISSUE TITLE
Some minor spelling errors on pop-ups

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#11]
On saving Project File, the dialog name is "Succes" - should be "Success"
On adding a email address to the Email List  "Successfull" - should be "Successful"
//I'll edit this list as I see them

**Comment by bogdanpopescu** [comment]
Fixed with the submission on 17th May ( Rlease_2.002 tag )

**Comment by bogdanpopescu** [comment]
@mtkuntz  Please verify it
