### ISSUE TITLE
Dependancies installer allows ver > lib_versions ie."newer than minimum

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#110]
the dependency installer grabs the latest version of mostly open-source code. we want the highest version that twister requires or has been tested-to. we do not want higher versions - untested or un-required just because they exist. Please change the installer.

if ver < lib_version:
        print('Testing dependency: Library `%s` has version `%s` and it must be `%s` or newer! Will install...' %
            (import_name, ver, lib_version))
    else:
        print('Testing dependency: Imported `%s` version `%s` is OK. No need to re-install.' % (import_name, ver))
        continue

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify it with 28th February load.

**Comment by mtkuntz** [comment]
Twister already includes some `tar.gz` files with libraries tested and compatible with Twister;they are located in `installer/packages`. We update these packages regularly.
The changes from 28 feb in the installer are making sure you are installing the libraries from `tar.gz` files first and ONLY IF they don't exist for a reason, the installer tries to install
the latest version from internet. If you don't delete the tar.gz file from `installer/packages`, the installer will never connect to internet. - BP

OK to CLOSE
