### ISSUE TITLE
login stalls 

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#113]
My login progress stalled
Twister running from applet
Authentication succeeded
C:\Users\mkuntz.twister\my-IP-address\Twister folder successfully created
C:\Users\mkuntz.twister\my-IP-address\Twister\XML folder successfully created
C:\Users\mkuntz.twister\my-IP-address\Twister\Users folder successfully created
C:\Users\mkuntz.twister\my-IP-address\Twister\config folder successfully created
C:\Users\mkuntz.twister\ Plugins folder found
CE client initialized: org.apache.xmlrpc.client.XmlRpcClient@df43b7
Getting folder: /home/mkuntz/twister/config/content
Server respons: {folder=true, data=/home/mkuntz/twister/config/, path=/, children=[Ljava.lang.Object;@1bdb13f}
Getting folder: /home/mkuntz/twister/configcontent

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 10th April. Please test.

**Comment by mtkuntz** [comment]
seems OK now
