### ISSUE TITLE
cli.py won't run

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#116]
pearl326:/home/mkuntz/twister/bin {127}cli.py --version
cli.py  2.020

pearl326:/home/mkuntz/twister/bin {128}cli.py
Username `user` must install Twister before using this script ! Exiting !

twister IS installed.
root     24957  3.0  1.1 2479204 91420 pts/7   Sl   14:02   4:55 /usr/local/bin/python2.7 -u /opt/twister/server/CentralEngine.py 8000

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please specify the login credentials like
./cli.py --login=mkuntz:your_passsword --version

If no credentials are specified, cli.py uses by default user:password and looks like user doesn't exists on your machine.

**Comment by mtkuntz** [comment]
does not work!
pearl326:/home/mkuntz/twister/bin {50}cli.py --server http://mkuntz:[mypid]@[server_ip]:8000/ --users
Username `user` must install Twister before using this script ! Exiting !

pearl326:/home/mkuntz/twister/bin {51}

**Comment by mtkuntz** [comment]
I was using an older format - works OK
