### ISSUE TITLE
File names in CONFIG list contain a trailing space.

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#118]
In the 28.03.2014 build, the file names stored in the CONFIG list contain a trailing space.
## If an element is passed directly to getConfig(), the method returns false.  When the trailing space is removed, the config parameters are returned.

From the init.py demo script:
<<< START filename: `1001:/home/choffman/twister/demo/testsuite-python/init.py` >>>

I am init file.
I am not doing anything special, just printing some variables.
Hello, user choffman !
System under test: /CJH.system
Exec process: pearl326_EP-1001
Suite: Test01
Config files: ['t1 ']
Properties: {'dependency': '', 'Run_Number': '1', 'twister_tc_revision': '-1'}

Remote file: /home/choffman/twister/demo/testsuite-python/init.py
Local file: /home/choffman/twister/.twister_cache/pearl326_EP-1001/init.py
<module 'ce_libs' from '/home/choffman/twister/.twister_cache/pearl326_EP-1001/ce_libs/ce_libs.py'>

> > > File `/home/choffman/twister/demo/testsuite-python/init.py` returned `PASS`. <<<

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Fix delivered on 10th April. Please test.
