### ISSUE TITLE
Unselecting an EP is not intuitive

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#120]
If an EP is already set in the SUT file, to unset it takes two steps. Should only be one.
I have to Select EP, then click on it to select it then again to de-select it,

![ep-set](https://cloud.githubusercontent.com/assets/4291929/2583845/99ea65d2-b9d6-11e3-81de-5582da6bc7a2.jpg)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 10th April. Please test.

**Comment by mtkuntz** [comment]
Fixed.
