### ISSUE TITLE
Components added to an SUT are not stored upon Save.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#122]
Components added to an SUT are not stored upon Save.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 10th April. Please test.

**Comment by mtkuntz** [comment]
Add/save now works. Delete/Save does not work. twister tries to delete a non-existent file using "id".json which is totally wrong. It should just remove the child (by its "id"), from inside the sut.json file.

**Comment by mtkuntz** [comment]
OK
