### ISSUE TITLE
DB connection is not consistent

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#123]
I've noticed that report tab doesn't work consistently while connecting to DB.

Say I've a DB user 'auto' as below ( using mysql )

create user 'auto'@'%' identified by 'twister';
create user 'auto'@'localhost' identified by 'twister';

grant all privileges on _._ to 'auto'@'localhost' with grant option;
grant all privileges on _._ to 'auto'@'%' with grant option;

and say twister server running at x.x.x.51 ip and I've configured the database section with following details,
Database: some_db
Server: x.x.x.52                      #where my DB server is running
User: auto
Password: twister

So when I click on report tab it works sometimes and sometimes I get error as below,

<methodResponse>
<fault>
<value>
<struct>
<member>
<name>faultCode</name>
<value>
<int>1</int>
</value>
</member>
<member>
<name>faultString</name>
<value>
<string>
(1045, "Access denied for user 'auto'@'x.x.x.51' (using password: YES)")
</string>
</value>
</member>
</struct>
</value>
</fault>
</methodResponse>

Manually I'm always able to connect to DB server without any problem, please let me know anything I'm missing.
Any help greatly appreciated.

Thanks,
Jai Shankar

**Comment by bogdanpopescu** [comment]
@jashanka 
ould you please let us know what is the GUI version and server ( /opt/twister/server/version.txt ) versions ?

**Comment by jashanka** [comment]
Gui version 2.0.40
Server 2.045

On Wednesday, 9 April 2014 11:58 AM, Bogdan Popescu notifications@github.com wrote:

@jashanka 
ould you please let us know what is the GUI version and server ( /opt/twister/server/version.txt ) versions ?

**Comment by jashanka** [comment]
Well, I also upgraded to latest twister server(3.021) and client and tested for the DB connectivity, but got the same error.

"(1045, "Access denied for user 'auto'@'x.x.x.51' (using password: YES)")"

**Comment by bogdanpopescu** [comment]
@jashanka 
Hi,
If it works intermitently, please upgrade to version uploaded on 11th April and retest.

**Comment by jashanka** [comment]
Thanks for the quick fix.

But while I found new build is fixed the DB problem, seems I'm facing one more.
i.e. Say user 'A' starts his client and logs into Twister and does his testing and logs out,
then user 'B' starts his client and logs into Twister and finishes his testing and logs out.

But after that subsequent login of user 'A' gets him all the paths and settings of user 'B', (this is applicable to all users who had logged in earlier as well ).

Could you please check on this.

Thanks,
Jai

**Comment by bogdanpopescu** [comment]
@jashanka 
Please close this one and open a new issue. Just FYI, I didn't reproduce the new one.

**Comment by jashanka** [comment]
Sure, Thanks.
