### ISSUE TITLE
Previous user paths are being loaded for current user, in Twister GUI.

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#124]
Following issue is seen while testing Twister server build 3.034( dated 11 April, 2014 ).

When user, say user ‘A’ logs in and logs out and say then user ‘B’ logs in logs out and does with his testing, later when user ‘A’ logs in back Twister loads all the ‘paths’ of user ‘B’ (this is true for all users who had logged in earlier). 

Please check on this,

Thanks,
Jai

**Comment by bogdanpopescu** [comment]
@jashanka 
What browser are you using ? We cannot reproduce it. Please make sure the users have different paths configured.

**Comment by jashanka** [comment]
I'm using mozilla ( also tried in chrome )

Could you please point out what exactly mean by 'users have different paths configured' ? 
(What I understand by this is, users twister client should be installed in their home directory).

I tried multiple times by installing the whole twister server and client freshly, changed browser but I haven't got rid of this problem.

Here are the exact steps I'm trying,
1. Installed twister dependency files/server as a root and installed twister client with user 'A' and then logged in with user 'B' installed twister client.
2. Copied all the files from twister/binaries/applet/\* to /var/www/html 
3. Started server (as root) and started client for 'A' (as user A) then started client for 'B' (as user B)
4. Opened the browser and connected to Twister server and logged in as 'A', now I'm able to see all paths of user 'A' under
       configuration/paths tab (like /home/A/...)
5. Now logged out and logged in as user 'B', now also all is fine
6. Only when I logged in again as 'A', now I see all paths of user 'B' under configuration/paths tab (like /home/B/...)

Not sure what I'm missing,

Thanks,
Jai

On Monday, 14 April 2014 12:25 PM, Bogdan Popescu notifications@github.com wrote:

@jashanka 
What browser are you using ? We cannot reproduce it. Please make sure the users have different paths configured.

**Comment by bogdanpopescu** [comment]
@jashanka 
Hi,

Could you check if the /home/A/twister/config/fwmconfig.xml is the same as /home/B/twister/config/fwmconfig.xml ? Could you check before ( when the paths are not the same ) and after ( when you see same paths ) the issue ?
Could you post them here ?
Thanks.

**Comment by jashanka** [comment]
I see they are fine, i.e. before and after the issue 'fwmconfig.xml' contains paths corresponding to user 'A' and 'B' in their respective paths.

Thanks,
On Friday, 18 April 2014 1:05 PM, Bogdan Popescu notifications@github.com wrote:

@jashanka 
Hi,
Could you check if the /home/A/twister/config/fwmconfig.xml is the same as /home/B/twister/config/fwmconfig.xml ? Could you check before ( when the paths are not the same ) and after ( when you see same paths ) the issue ?
Could you post them here ?
Thanks.

**Comment by jashanka** [comment]
Posting the paths of user 'jai' and 'balu' (contents of 'fwmconfgi.xml' are same before and after path change)

<?xml version="1.0" encoding="UTF-8" standalone="no"?>



<Root>
    <FileType>config</FileType>
    <TestCaseSourcePath>/home/balu/twister/demo</TestCaseSourcePath>
    <UsersPath>/home/balu/twister/config/projects</UsersPath>
    <GlobalParams>/home/balu/twister/config/globals.xml</GlobalParams>
    <DbConfigFile>/home/balu/twister/config/db.xml</DbConfigFile>
    <EmailConfigFile>/home/balu/twister/config/email.xml</EmailConfigFile>
    <GlobalParams>/home/balu/twister/config/globalparams.xml</GlobalParams>
    <LibsPath>/home/balu/twister/libs</LibsPath>
    <PredefinedSuitesPath>/home/balu/Documents</PredefinedSuitesPath>
    <TestConfigPath>/home/balu/Documents</TestConfigPath>
    <ArchiveLogsPath>/home/balu/twister/logs_archive</ArchiveLogsPath>
    <ArchiveLogsPathActive>false</ArchiveLogsPathActive>
    <SysSutPath>/opt/twister/config/sut</SysSutPath>
    <SutPath>/home/balu/twister/config/sut</SutPath>
    <LogsPath>/home/balu/twister/logs</LogsPath>
    <LogFiles>
        <logRunning>log_running.log</logRunning>
        <logDebug>log_debug.log</logDebug>
        <logSummary>log_summary.log</logSummary>
        <logTest>log_test.log</logTest>
        <logCli>CLI.log</logCli>
    </LogFiles>
</Root>

<?xml version="1.0" encoding="UTF-8" standalone="no"?>



<Root>
    <FileType>config</FileType>
    <TestCaseSourcePath>/home/jai/twister/demo</TestCaseSourcePath>
    <UsersPath>/home/jai/twister/config/projects</UsersPath>
    <GlobalParams>/home/jai/twister/config/globals.xml</GlobalParams>
    <DbConfigFile>/home/jai/twister/config/db.xml</DbConfigFile>
    <EmailConfigFile>/home/jai/twister/config/email.xml</EmailConfigFile>
    <GlobalParams>/home/jai/twister/config/globalparams.xml</GlobalParams>
    <LibsPath>/home/jai/twister/libs</LibsPath>
    <PredefinedSuitesPath>/home/jai/Documents</PredefinedSuitesPath>
    <TestConfigPath>/home/jai/Documents</TestConfigPath>
    <ArchiveLogsPath>/home/jai/twister/logs_archive</ArchiveLogsPath>
    <ArchiveLogsPathActive>false</ArchiveLogsPathActive>
    <SysSutPath>/opt/twister/config/sut</SysSutPath>
    <SutPath>/home/jai/twister/config/sut</SutPath>
    <LogsPath>/home/jai/twister/logs</LogsPath>
    <LogFiles>
        <logRunning>log_running.log</logRunning>
        <logDebug>log_debug.log</logDebug>
        <logSummary>log_summary.log</logSummary>
        <logTest>log_test.log</logTest>
        <logCli>CLI.log</logCli>
    </LogFiles>
</Root>

On Friday, 18 April 2014 1:05 PM, Bogdan Popescu notifications@github.com wrote:

@jashanka 
Hi,
Could you check if the /home/A/twister/config/fwmconfig.xml is the same as /home/B/twister/config/fwmconfig.xml ? Could you check before ( when the paths are not the same ) and after ( when you see same paths ) the issue ?
Could you post them here ?
Thanks.

**Comment by bogdanpopescu** [comment]
@jashanka 
Fix provided on 25th April, please verify it.

**Comment by jashanka** [comment]
Thanks Bogdan.
