### ISSUE TITLE
Unable to add properties to testbed devices after level two

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#125]
# This is unfortunate that I've to raise this third bug consecutively, though thanks for the quick support/response.

In twister GUI testbed section, I'm trying to add device as in below structure, say,

device : D
under that first component : C
and under C one more component : C1

after that I'm trying to add properties to C1 ( from the right pane), giving 
name : abc
and value : xyz

and then when I press update button, I get the following error:

"ERROR" User jai: Set Device: Cannot access parent path or ID '/C'!

similarly I can't add any properties to components that are after level two, but I notice we can add properties to D and C without any issue.

[From a quick debug I found, (when I try adding the above property to C1) in file server/CeResource.py at line 1268, the value of parent is /C, which I suppose should be /D/C]

Thanks,
Jai

**Comment by bogdanpopescu** [comment]
@jashanka 
Fix provided in GUI side. Please verify.

**Comment by jashanka** [comment]
It's not working, I'm still hitting the same issue.

**Comment by bogdanpopescu** [comment]
@jashanka 
Hi,

Can you confirm that you copied all content from binaries/applet directory into your www directory ?
Can you confirm that the GUI version is 3.016, build date 28.04.2014 ? ( check in Configuration->About ).
We tested up to level 5 without issues.
![for_issue_125](https://cloud.githubusercontent.com/assets/1727668/2838685/407fcf22-d039-11e3-85e3-92866b249bb1.png)

**Comment by jashanka** [comment]
Sorry, my bad I missed to copy binaries/applet file.
Thank you.
