### ISSUE TITLE
demo Perl script always return "None" to framework so perl tests always fails

### ISSUE THREAD

**Issue by popwich** [Luxoft/Twister#126]
/demo/testsuite-perl/test001.plx contans below code to call inline python from perl:

(use Inline Python => <<"END_OF_PYTHON_CODE";
 import os, sys
 sys.path.append(os.getenv("HOME") + "/.twister_cache/")
 from ce_libs import logMsg
 END_OF_PYTHON_CODE)

bug 1: there is no ce_libs python file in: /home/user/.twister_cache/ folder
bug 2: located ce_libs.py in /home/user/twister/.twister_cache/ folder, but still can't import logMsg method because it doesn't exist in ce_libs.py. 
bug 3: found logMsg method is contained in TscCommonLib.py in /home/user/twister/.twister_cache/ folder, try to load logMsg from TscCommonLib.py, but now perl script will fail at: 
"logMsg("logTest", "\nTestCase: $testName starting\n");"

without logMsg working, perl script will always return 'None' to framework even with "return $error_code"  in test which will fail the test always. 

EP_cli logs shows: 
<<< File `/home/user/workspace/Python_twisterdemo/Source/demo/testsuite-perl/test001.plx` returned `NONE`. <<<

**Comment by popwich** [comment]
can anyone pls help look into this issue? thanks

**Comment by bogdanpopescu** [comment]
@popwich 
We are looking into it.

**Comment by bogdanpopescu** [comment]
@popwich 
The issue is fixed, please verify.
