### ISSUE TITLE
Using Cron style configuration of Test Scheduling.

### ISSUE THREAD

**Issue by ljones-cbnl** [Luxoft/Twister#127]
Hi

I understand the scheduler plugin and how to set up time based triggers for projects.
i.e. once, daily, weekly.

I would like to see this feature extended into the project configuration gui, each project would have its own configuration with a tick box to enable the time trigger and a text entry box to accept multiple lines of text specifying the time to trigger in the cron format.
i.e.

<pre>
# Minute  Hour    Day of Month       Month         Day of Week
# (0-59) (0-23)    (1-31)        (1-12 or Jan-Dec)(0-6 or Sun-Sat)                
    15    20-23/2    *              *                 1-5
    15    0-7/2      *              *                 1-5
</pre>

This example triggers every 2 hours at 15mins past the hour, between 8pm and 7am on Monday to Friday.

My use case is as above, I want to test a project multiple time throughout the night and adding/changing 6 entries to the scheduler on a daily bases for the above example is time consuming.
Another use case is to trigger a test every 15minutes starting midnight Friday and stopping midnight Sunday. This gives a total of 192 triggers and is beyond my patience as a software engineer.
As a work around  I am investigating using this feature in Jenkins to trigger Twister into performing the required project and test cases.

Regards

Lloyd Jones

**Comment by bogdanpopescu** [comment]
@ljones-cbnl 
Hi,

This could be covered using the cli.py, it can be added into crontab to execute a project. Would that work for you ?

Regards,
Bogdan Poepscu.

**Comment by ljones-cbnl** [comment]
@bogdanpopescu 
Hi
That is another work around, currently Jenkins is triggering the project EPs using the CLI.py, so using cron would perform the same actions. 

My main point of investigation now is to find how to move the stored xml project configuration from the file to the EPs so that any changes made in the GUI will be used the next time a triggered test sequence occurs. At the moment I have to run the tests from the GUI for this to happen.

My main reason for getting involved with Twister is using the GUI to allow our software engineers to quickly and easily make additions/alterations etc. to test cases.
I have looked at Jenkins and although it has a rich feature set I am unable to find a GUI frontend that allows for testcase execution to be graphically changed using tick boxes. 
This is handled fairly well using the Twister Java GUI.

Thank you for responding so quickly.

Regards

Lloyd

**Comment by bogdanpopescu** [comment]
@ljones-cbnl 
We can provide a way to export the project file for cli execution. You can define everything in GUI ( select test cases, select SUT -> EP , ... ) then export for CLI. The exported file can be loaded by cli.py and you will be able to trigger execution of project files from crontab.

Regards,
Bogdan.

**Comment by ljones-cbnl** [comment]
Hi Bogdan
That sounds like a solution, can the export be triggered from the cli.py or will it have to be an additional manual process performed by the user? I would preferably it would be a CLI.py step in the cron job, that way the latest configuration will be used.

I have been experimenting with the scheduler and I see a similar problem occurring there. 
If I have a project with 2 suites each with 2 tests, and I enable them all. 
In the scheduler I have it set to executes the project once, a second task waits 10 minutes before executing the project again. In this 10 minutes I change the ticks to disable the 2nd suite and save the project. 
When the second task is executed after 10 minutes it executes all 4 tests, I would expect it to only execute the 1st suite, 2 tests.
Should I report that in a separate issue so we can discuss and track separately to this issue of "external triggering"?

Regards

Lloyd

**Comment by bogdanpopescu** [comment]
@ljones-cbnl 
The export cannot be triggered by cli.py, it will have to be done from GUI. There are some information generated by GUI that is not incorporated in cli.py and we would like to encourage GUI usage as much as possible.
Please raise a separate issue for scheduler so we can track it separately.

**Comment by bogdanpopescu** [comment]
@ljones-cbnl 
Delievred support for crontab execution using cli.py. The project files can be exported from GUI for cli run using Project tab, File->Save for CLI option. 
The saved file must be passed to cli.py as the project file, e.g.:
./cli.py --server <server>:<port> --login <user>:<pass> -c ~/twister/config/fwmconfig.xml -p ~/twister/config/users/test_cli.xml -s start

Please verify.

**Comment by ljones-cbnl** [comment]
Hi Bogdan
Thanks for the support, it will be some time in the beginning of next week before I can get back onto Twister and verify your delivery, I will hopefully get back to you middle of next week.
Thanks
Lloyd

**Comment by bogdanpopescu** [comment]
@ljones-cbnl 
Hi,
Could you verify if this is working ?

**Comment by ljones-cbnl** [comment]
Hi
My apologies we have been working on testing a release of code, I am still interested and will test as soon as I can.
Lloyd
