### ISSUE TITLE
Cannot remove testbed component

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#129]
After creating a new testbed, I want to remove a component, but it is not removed

I created a component in a new testbed, but decided I did not want it.  When I tried to remove it, it did not.  There were no popup warnings or errors. Unlike issue 1, the JAVA Console did not show anything at all when I hit the Remove button.  Attached is a screen shot.
![componentnotremoved](https://cloud.githubusercontent.com/assets/3911048/3151013/a85361b4-ea7d-11e3-9293-d649d533d8dd.JPG)

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Hi,
Fix delivered on 6th June, please verify.

**Comment by CJHoffmann** [comment]
Verified
