### ISSUE TITLE
Remove Luxoft from default email authorization and email list

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#13]
If/When our IT department begins to evaluate Twister and allow it on our network, I do not want to have to explain why our test reports, by default are being sent to Luxoft.

**Comment by bogdanpopescu** [comment]
@CJHoffmann  Fixed in tag 31_05_2013. Please verify

**Comment by CJHoffmann** [comment]
A bogus email address was replaced for the luxoft address.
The expectation was the default address was not none.

**Comment by bogdanpopescu** [comment]
Ok, @CJHoffmann please let me know what email address to put by default.

**Comment by CJHoffmann** [comment]
My preference would be to leave the email address blank.  If an example is needed, please put it in the documentation.

**Comment by bogdanpopescu** [comment]
@CJHoffmann  Ok, I updated the email.xml file to remove the email addresses. I think the issue can be close now.

**Comment by CJHoffmann** [comment]
After creating a new client, the email configuration fields are empty.
