### ISSUE TITLE
Cannot update testbed component properties

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#130]
I can create properties for components I created, but when I try to enter a value and hit the Update button an Error Popup message “_ERROR_ User testuser: Set Device: Cannot access parent path or ID ‘/SLOT12’!”  appears and the value is not updated.  I am able to update properties for /SLOT12.
Attached is a screen shot .  
![doesnotsavechild](https://cloud.githubusercontent.com/assets/3911048/3151031/eea27ff6-ea7d-11e3-8653-1631a7c617d4.JPG)
I took a quick look at the json file and noticed that there are no path attributes in this testbed except at the topmost levels.

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Hi,
Fix delivered on 6th June, please verify.

**Comment by CJHoffmann** [comment]
Verified
