### ISSUE TITLE
Multiple User Log in failure

### ISSUE THREAD

**Issue by leanderc** [Luxoft/Twister#131]
![java auth](https://cloud.githubusercontent.com/assets/8088089/3493354/5133108c-05b7-11e4-9ae0-9bff9caecdd1.jpg)

Unable to Log in with any other user other than 'user' and 'password' as mentioned in the user guide documentation.
Created another user named 'selenium' with admin access privileges but was unable to log in with the same,
The error was asking for java authentication which is 'user' / 'password' . but obviously the other users would not know about other admin credentials.
Screen shot attached

**Comment by bogdanpopescu** [comment]
@leanderc 
Hi,

The user 'selenium' must be a valid Linux user on the machine where Twister is installed. Also, it has to have a Twister client installed.

**Comment by leanderc** [comment]
Hi ,

Yes selenium is a valid linux user , and Twister client is installed.

**Comment by bogdanpopescu** [comment]
@leanderc 
Did you added selenium user in file /opt/twister/config/users_and_groups.ini ?

**Comment by leanderc** [comment]
The user selenium  is able to log in provided the credentials "user" / "password" is specified in the java dialog

**Comment by bogdanpopescu** [comment]
@leanderc 
Please answer the previous question.
Did you added selenium user in file /opt/twister/config/users_and_groups.ini ?

**Comment by leanderc** [comment]
Yes
[[selenium]]
        groups_production = 
        groups_development = admin
        key = 35ba0ce65084c7e44632e274e568ae3b
        timeout = 00

**Comment by bogdanpopescu** [comment]
@leanderc 
Ok, then in the Java window ( the one with red ) enter the credentials for selenium user.

**Comment by leanderc** [comment]
Nope , Still need to enter user/password in the java window.
selenium user credentials wont work

**Comment by leanderc** [comment]
@bogdanpopescu 

Hi Bogdan,
Were you able to reproduce this error? Do you need any more data ?

**Comment by bogdanpopescu** [comment]
@leanderc 
No, we cannot reprodfuce it. 
Can you ssh to Twister server using selenium credentials ?

**Comment by leanderc** [comment]
@bogdanpopescu 
Yes we can ssh using selenium credentials
We have a twister ubuntu server vm which has a designated local EP. This has the credentials user/password and selenium/selenium which we can ssh with.
Then there is a selenium VM with twister client installed. This  has credentials selenium/selenium. We can SSH to this VM.How ever we cannot access the UI with these credentials.
We also have a windows box from where we can access the twister with user/password but can not access it with selenium user credentials.Error as above.

Could you cross validate these steps and specify if we are doing anything wrong ?

**Comment by bogdanpopescu** [comment]
@leanderc 
from your comment I understand that Twister server and Twister client are installed on different machines ( VMs ). Is this true ? If so, the selenium user must be able to ssh into Twister server as well.

**Comment by leanderc** [comment]
@bogdanpopescu 
Here is what we did again

Installed twister server and client on the same machine the only difference is the user is not ''úser'' and 'password'
created user 'leander' with password 'leander' . This user leander can ssh to the machine.
CE page loads just fine. 
The applet page loads up but when login is clicked , nothing happens

**Comment by bogdanpopescu** [comment]
@leanderc 
Hi,
I updated the GUI binaries, apparently there was an issue there. Please use the latest binaries from binaries/applet directory to copy them in /var/www/twister. Let me know how it goes.
Thanks.

**Comment by leanderc** [comment]
@bogdanpopescu 

Downloaded twister git branch
installed twister , created new user from the ui and tried logging with that , got the same error
java  authentication

**Comment by bogdanpopescu** [comment]
@leanderc 
Any errors/messages in /opt/twister/server_log.log ?

**Comment by bogdanpopescu** [comment]
@leanderc 
Any update here ?
