### ISSUE TITLE
Custom Plugins wont show.

### ISSUE THREAD

**Issue by leanderc** [Luxoft/Twister#132]
![plugins](https://cloud.githubusercontent.com/assets/8088089/3493470/8af9c4a4-05b8-11e4-8a47-8add7f78b5f5.jpg)

Wrote a custom plugin using the steps mentioned in the documentation , we can see the plugin.jar in the Remote plugin section with a download button next to it , but cannot load it into the list of available plugins.
Screen shot attached

**Comment by bogdanpopescu** [comment]
@leanderc 
Hi,

The plugins documentation has been updated and posted on twistertesting.com. Please update your code to comply with the latest changes,

**Comment by leanderc** [comment]
@bogdanpopescu 

Ww folowed the latest Document , and created a Jar as mentioned in the Document .The Jar shows in the Local plugins section but there is no way of adding it to the list of available plugins.
Do we need to edit some xml or something for it to show?

**Comment by leanderc** [comment]
@bogdanpopescu  - What information do you need.
We are consistently facing this issue. Following the document of the plugin guide mentioned in the website.

**Comment by bogdanpopescu** [comment]
@leanderc 
I added a sample plugin in plugins directory to show how the skeleton must look like. The file is SamplePlugin.java. You can use buildSamplePlugin.sh ( ./buildSamplePlugin.sh ) to build SamplePlugin.jar file. Once SamplePlugin.jar is created, you have to copy it into /opt/twister/plugins directory. Logoff and login in Twister and verify if the SamplePlugin is shown in the list of available plugin.
Hope this helps.
