### ISSUE TITLE
Unable to execute Selenium based tests

### ISSUE THREAD

**Issue by leanderc** [Luxoft/Twister#133]
Added Selenium based tests to a test suite , made changes to the python scripts as mentioned in the online documentation , followed the steps mentioned in the documentation yet couldn't execute selenium tests.
Logs as below.

Downloading library `TscCommonLib.py` …
… all libraries downloaded.

===== ===== ===== ===== =====
Starting suite `101 – Selenium`
===== ===== ===== ===== =====

<<>>

Test case exception:
File “ExecutionProcess.py”, line 975, in tests
result = current_runner._eval(str_to_execute, globs, args)
File “C:\Selenium\client\executionprocess\RunnerClasses.py”, line 247, in _eval
execfile(fpath, globs_copy)
File “C:\Selenium\client\executionprocess/.twister_cache/SeleniumRemote/Selenium_appd_login.py”, line 10, in
import TscUnitTestLib as unittest
ImportError: No module named TscUnitTestLib

**Comment by bogdanpopescu** [comment]
@leanderc

ImportError: No module named TscUnitTestLib
Did you selected the TscUnitTestLib from liraries ?

![libraries](https://cloud.githubusercontent.com/assets/1727668/3520153/cc0cdce2-072a-11e4-85cf-5e4f0e32eba4.png)
