### ISSUE TITLE
Test Suite appears blank after reloading the suite xml

### ISSUE THREAD

**Issue by leanderc** [Luxoft/Twister#134]
![editaftertestrun](https://cloud.githubusercontent.com/assets/8088089/3493733/202c128c-05bb-11e4-9e8c-534d6dea47e0.jpg)

After a testcase suite is run , if we reload from an existing xml , the testcases wont show as per screen shot.

**Comment by bogdanpopescu** [comment]
@leanderc 
Please let me know the GUI version ( Configuration->About )

**Comment by leanderc** [comment]
Twister Framework 
V.: 3.021 
Build date: 10.06.2014
x86_64 Linux, Ubuntu 12.04 precise
Python 2.7.3.final.0

**Comment by bogdanpopescu** [comment]
@leanderc 
We cannot reproduce. 
Please activate the java log, reproduce the issue and send the java log.

**Comment by leanderc** [comment]
@bogdanpopescu 

This occurs when you change the file system path of the test cases and load an xml containing pointing to another path .There should be a validation which says testcases not found.

**Comment by bogdanpopescu** [comment]
@leanderc 
This is a configuration issue. Anyway, we will work to add a warning message.

**Comment by leanderc** [comment]
@bogdanpopescu  - The problem occurs when there are different people working on the same project..the test model / xml is created by a different person and the test suite is created by another.Agree that it is a configuration issue but this is hard to figure from the twister UI
