### ISSUE TITLE
error while starting twister client 

### ISSUE THREAD

**Issue by Raju-Penumatsa** [Luxoft/Twister#137]
I am seeing the below error while starting twister client on linux.

My Pc and env details 
python : 2.7 version 
linux : scientific linux 6.3  

  File "/home/user/twister/bin/start_client.py", line 887
    tagsDict = {title:descr for title, descr in tags}
                              ^
SyntaxError: invalid syntax

**Comment by bogdanpopescu** [comment]
@bangi123 
The script is not executed with python 2.7. 
Edit start_client ( not start start_client.py ) and set the path for PYTHON_PATH to point to python2.7

**Comment by bogdanpopescu** [comment]
@bangi123 
Any update here ? Can we close the issue ?
