### ISSUE TITLE
Java applet webpage will not load

### ISSUE THREAD

**Issue by evopkay** [Luxoft/Twister#138]
@promihu @VasiliyS @dcioata 
@elenabratanova @bogdanpopescu 

http://192.168.122.166/twister
Not Found
The requested URL /twister was not found on this server.
Apache/2.4.7 (Ubuntu) Server at 192.168.122.166 Port 80

As per the Document
5. Install Apache and start the service; make sure the document root is set to /var/www
How ever it dosent mention where to set document root to.
Edited httpd.conf and added the below entries

ServerName pepper-virtual-machine
DocumentRoot "/var/wwww"

Also did step number 6
6. Make /var/www/twister directory and copy twister/binaries/applet/\* into this directory

CE engine page loads
http://192.168.122.166:8000/web/

IP and Port 192.168.122.166:8000
Machine pepper-virtual-machine
System  Peppermint 5 trusty
Server Type no_type
Server Version  3.042

Please check.

**Comment by bogdanpopescu** [comment]
@evopkay 
This is an apache configuration issue. 
The document root should be set in /etc/apache2/sites-enabled/000-default file, like this:

VirtualHost *:80
    ServerAdmin webmaster@localhost

```
DocumentRoot /var/www
<Directory />
    Options FollowSymLinks
    AllowOverride All
</Directory>
<Directory /var/www/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
    AddHandler mod_python .py
</Directory>
```

**Comment by evopkay** [comment]
@promihu @VasiliyS @dcioata
@elenabratanova @bogdanpopescu 

This didnt work , same issue persists.
Does twister need to be in a domain as the machine accessing the java applet UI?

Installed twister on a ubuntu 12.04 server with the steps mentioned in the document.
Was able to see the twister UI but not able to log in.
Apart from the user/password mentioned in the document , everything else was copied verbatim.

Also assigned the respective roles to the user we created in users and groups.ini
Was able to reach the log in page but when clicking login , nothing happened.Why ?

Also no logs were shown in the CE interface logging.

**Comment by bogdanpopescu** [comment]
@evopkay 
If you get the Twister welcome page and you cannot connect to Twister, please get the latest binaries of GUI from binaries/applet directory and copy them in /var/www/twister. We updated a few minutes ago a fix for GUI.

**Comment by bogdanpopescu** [comment]
@evopkay 
Any update on this issue ?
