### ISSUE TITLE
GITPlugin Tab not being displayed

### ISSUE THREAD

**Issue by bjrr** [Luxoft/Twister#140]
Hi,

I have installed the Jenkins and Git plugins. The Jenkins tab shows up but the Git tab does not. Below is a log of issues that was being displayed.  Also a screen shot is below. Please let me know what to do to get the GIT plugin working.
14-08-06 14:09:20  INFO     [06/Aug/2014:14:09:20] HTTP 
Request Headers:
  AUTHORIZATION: Basic dXNlcjpwYXNzd29yZA==
  Content-Length: 194
  PRAGMA: no-cache
  COOKIE: session_id=285bfe814ef63d8c46ab5174ee7f30d83662b92a
  HOST: rtxttalp01:8000
  CONNECTION: keep-alive
  CACHE-CONTROL: no-cache
  Remote-Addr: 168.127.204.95
  ACCEPT: text/html, image/gif, image/jpeg, _; q=.2, */_; q=.2
  USER-AGENT: Apache XML RPC 3.1.3 (Sun HTTP Transport)
  Content-Type: text/xml
14-08-06 14:09:20  ERROR    [06/Aug/2014:14:09:20] HTTP Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/twister/server/CeXmlRpc.py", line 93, in default
    resp = super(CeXmlRpc, self).default(_vpath, *_params)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cptools.py", line 371, in default
    raise Exception('method "%s" is not supported' % attr)
Exception: method "listFiles" is not supported

![image](https://cloud.githubusercontent.com/assets/8376685/3833212/1f342d72-1da5-11e4-97d0-fbd3759b916d.png)

**Comment by leanderc** [comment]
@bjrr  - What is the procedure followed to install the plugins?

**Comment by bjrr** [comment]
@leanderc I used:
sudo cp ./Twister/binaries/GitPlugin/Git/\* /opt/twister/plugins

Same thing for Jenkins, Jenkins plugin worked fine but Git did not, Please help.

**Comment by bjrr** [comment]
@leanderc   any ideas?

**Comment by bogdanpopescu** [comment]
@leanderc  @bjrr 
This is a bug, we'll fix it today and post the updated code.

**Comment by bogdanpopescu** [comment]
@bjrr 
Hi,
We posted a new version of GITPlugin to fix the issue, please verify.

**Comment by bjrr** [comment]
I still have the same issue. I downloaded the new plugins and the GITplugin tab still does not show up. I downloaded the Jenkins Plugin and it works fine.

**Comment by bogdanpopescu** [comment]
@bjrr 
Hi,
Please update to the latest, we submited a new version.

**Comment by bjrr** [comment]
I have updated to the latest and still see the same exact problem. Can you please elaborate on anything that I need to do that would allow the tab to show up?

**Comment by bogdanpopescu** [comment]
@bjrr 
Hi,

In your client home directory, you should find the configuration file twister/config/plugins.xml. Pleaase check in this file if you have a section like this:

```
<Plugin>
    <name>GITPlugin</name>
    <jarfile>GITPlugin.jar</jarfile>
    <pyfile>GITPlugin.py</pyfile>
    <status>enabled</status>
    <property>
        <propname>path</propname>
        <propvalue>/home/tscguest/teste</propvalue>
    </property>
</Plugin>
```

Probably the value of the path property is set to /home/tscguest and it cannot be found on your system. 
If so, de-activate the plugin, remove the entire GITPlugin section and try to reactivate. 
To get some debug info, please activate the GUI java console and check for errors when plugin is activated.

Best.

**Comment by bjrr** [comment]
The issue is still unresolved. The value referenced above is not the same as what is in twister/config/plugins.xml. The path is currently as follows:
<Plugin>
        <name>GITPlugin</name>
        <jarfile>GITPlugin.jar</jarfile>
        <pyfile>GITPlugin.py</pyfile>
        <status>enabled</status>
        <property>
            <propname>path</propname>
            <propvalue>/home/user</propvalue>
        </property>
    </Plugin>
    <Plugin>
        <name>Jenkins</name>
        <jarfile>JenkinsPlugin.jar</jarfile>
        <pyfile>JenkinsPlugin.py</pyfile>
        <status>disabled</status>
        <property>
            <propname>script</propname>
            <propvalue>/home/user/jenkins/build_script.sh</propvalue>
        </property>
        <property>
            <propname>tests</propname>
            <propvalue>/home/user/twister/config/testsuites.xml</propvalue>
        </property>
    </Plugin>

**Comment by bjrr** [comment]
@bogdanpopescu <Plugin>
        <name>GITPlugin</name>
        <jarfile>GITPlugin.jar</jarfile>
        <pyfile>GITPlugin.py</pyfile>
        <status>enabled</status>
        <property>
            <propname>path</propname>
            <propvalue>/home/user</propvalue>
        </property>
    </Plugin>"

**Comment by Derrick-Liew** [comment]
Hi,

Got the latest download from "git_hub_branch", the tab for GITPlugin is still not displayed when the "Activate" is ticked. Please advise.
