### ISSUE TITLE
Starting client services automatically

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#142]
Hi,

```
This is a query,
```

We wanted user client service to be started automatically if it has not started already whenever a user logs into Twister from GUI. For that we had added a check in /etc/profile and it was working fine till April 2014.

But in Twister build after April we found when a user logs in from GUI it's not making ssh to the Linux machine and hence /etc/profile is not getting executed.

Could you please suggest a workaround so that how can any users client can be started automatically?

Thanks,
Jai

**Comment by bogdanpopescu** [comment]
@jashanka 
Hi,
You can start automatically the clients using a script that is executed at boot. You can create a script, save it in /etc/init.d and create a link to it in /etc/rc3.d ( or whatever init level you are using ) with S99 prefix ( to be executed latest ).. For instance, if your script is called start_twister_clients , you have to create a link S99start_twister_clients.
In this script, you can add the command
su - username -c '/home/username/twister/bin/start_client start'
for every user that needs the twister client ( replace username with the real user )

I hope this helps.

**Comment by bogdanpopescu** [comment]
@jashanka 
Did you try it ?
