### ISSUE TITLE
Log records being duplicated in reports

### ISSUE THREAD

**Issue by leanderc** [Luxoft/Twister#143]
![logerror_twister](https://cloud.githubusercontent.com/assets/8088089/4113636/f6374144-3252-11e4-8bdd-10dd608e19a6.jpg)

@bogdanpopescu 

In this latest release , we noticed that log records were being duplicated in the twister_demo database and we are able to see redundant logs in the UI.
Take a look at the screen shot.

**Comment by leanderc** [comment]
@bogdanpopescu 
Any updates on this ?

**Comment by leanderc** [comment]
@bogdanpopescu 
If you can let us know if this is a Bug / under investigation / need more info .It will help us design our reports accordingly.

**Comment by bogdanpopescu** [comment]
@leanderc 
Hi, 

We cannot reproduce this issue, could you share with me the /opt/twister/server_log.log file ?

**Comment by leanderc** [comment]
@bogdanpopescu 

![server_log](https://cloud.githubusercontent.com/assets/8088089/4540793/b623e326-4e0b-11e4-9799-4b3d3debcfda.png)
Uploaded log as a png file. rename it to log.

Nothing significant is worth mentioning in the logs.

**Comment by bogdanpopescu** [comment]
@leanderc 
I cannot see the image. 
Anyway, please enable DEBUG tracing level ( go in /opt/twister/bin and run python set_log_level.py DEBUG ), run your test(s) and save to database. In the /opt.twister/server_log.log file, you should see the trace when the information is saved into DB, similar with the following
DEBUG    CeProject.py: 3331: save_to_database  Executed query .... 

Please let me know how many tests you are running and how many times you see the save_to_database trace into your server_log.log file.

**Comment by leanderc** [comment]
@bogdanpopescu 

Ran 1 test but save_to_database is seen 2 times in the trace logs
Logs attached below.

---

14-10-08 09:45:11  DEBUG    CeProject.py: 3486: save_to_database  Executed query `INSERT INTO results
                ( run_nb,username,ce_hostname,ce_ip,ep_ip,ep_hostname,ep_name,suite_name,tc_name,tc_path,tc_status,tc_time_elapsed,tc_date_started,tc_date_finished,tc_log,project_id,infra_id,test_id )
                VALUES (22, 'vmware', 'Twister-Leander', '127.0.1.1', '127.0.1.1', 'Twister-Leander', 'twister-leander_EP-vmware', 'test22', 'Test_verifyIpAddress.py', '/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py', 'FAIL', '10', '2014-10-08T09:44:43.179636', '2014-10-08T09:44:54.086101', '<<< START filename: `1001:/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py` >>><br>\n<br>\nConfigstore Library: Invoked<br>\nvCo Library: Invoked<br>\nFetched global parameters successfully<br>\nGenerated input for vCO workflow verifyIpAddress<br>\nFetched vCO details successfully<br>\nUnable to fetch workflowid for workflow verifyIpAddress<br>\n<br>\nTest case exception:<br>\nFile \"/home/vmware/twister/client/executionprocess/ExecutionProcess.py\", line 1088, in tests<br>\n    result = current_runner._eval(str_to_execute, globs, args)<br>\n  File \"/home/vmware/twister/client/executionprocess/RunnerClasses.py\", line 266, in _eval<br>\n    execfile(fpath, globs_copy)<br>\n  File \"/home/vmware/twister/.twister_cache/twister-leander_EP-vmware/Test_verifyIpAddress.py\", line 61, in <module><br>\n    _RESULT = verifyIpAddress()<br>\n  File \"/home/vmware/twister/.twister_cache/twister-leander_EP-vmware/Test_verifyIpAddress.py\", line 59, in verifyIpAddress<br>\n    error_code =  vco_obj.executevcoworkflow(input,project_id,infra_id,test_id,cnf_obj)<br>\n  File \"/home/vmware/twister/.twister_cache/twister-leander_EP-vmware/ce_libs/Lib_vCO.py\", line 124, in executevcoworkflow<br>\n    vco_url = \"https://\" + vco_user + \":\" + vco_pswd + \"@\" + vco_ip + \":\" + vco_port + \"/vco/api/workflows/\" + workflow_id + \"/executions/\"<br>\nTypeError: coercing to Unicode: need string or buffer, NoneType found<br>\n<br>\n>>> File `/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py` execution CRASHED. <<<<br>\n<br>\nTest statistics: Start time 2014-10-08 09:44:43 -- End time 2014-10-08 09:44:54 -- 11.15 sec.<br>\n<br>\n<<< END filename: `1001:/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py` >>>', 'demo', 'demo', 'demo')` OK.
14-10-08 09:45:11  DEBUG    CeXmlRpc.py: 614: commit_to_database  CE: Saving to database was successful!

---

14-10-08 09:45:12  DEBUG    CeProject.py: 3486: save_to_database  Executed query `INSERT INTO results
                ( run_nb,username,ce_hostname,ce_ip,ep_ip,ep_hostname,ep_name,suite_name,tc_name,tc_path,tc_status,tc_time_elapsed,tc_date_started,tc_date_finished,tc_log,project_id,infra_id,test_id )
                VALUES (22, 'vmware', 'Twister-Leander', '127.0.1.1', '127.0.1.1', 'Twister-Leander', 'twister-leander_EP-vmware', 'test22', 'Test_verifyIpAddress.py', '/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py', 'FAIL', '10', '2014-10-08T09:44:43.179636', '2014-10-08T09:44:54.086101', '<<< START filename: `1001:/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py` >>><br>\n<br>\nConfigstore Library: Invoked<br>\nvCo Library: Invoked<br>\nFetched global parameters successfully<br>\nGenerated input for vCO workflow verifyIpAddress<br>\nFetched vCO details successfully<br>\nUnable to fetch workflowid for workflow verifyIpAddress<br>\n<br>\nTest case exception:<br>\nFile \"/home/vmware/twister/client/executionprocess/ExecutionProcess.py\", line 1088, in tests<br>\n    result = current_runner._eval(str_to_execute, globs, args)<br>\n  File \"/home/vmware/twister/client/executionprocess/RunnerClasses.py\", line 266, in _eval<br>\n    execfile(fpath, globs_copy)<br>\n  File \"/home/vmware/twister/.twister_cache/twister-leander_EP-vmware/Test_verifyIpAddress.py\", line 61, in <module><br>\n    _RESULT = verifyIpAddress()<br>\n  File \"/home/vmware/twister/.twister_cache/twister-leander_EP-vmware/Test_verifyIpAddress.py\", line 59, in verifyIpAddress<br>\n    error_code =  vco_obj.executevcoworkflow(input,project_id,infra_id,test_id,cnf_obj)<br>\n  File \"/home/vmware/twister/.twister_cache/twister-leander_EP-vmware/ce_libs/Lib_vCO.py\", line 124, in executevcoworkflow<br>\n    vco_url = \"https://\" + vco_user + \":\" + vco_pswd + \"@\" + vco_ip + \":\" + vco_port + \"/vco/api/workflows/\" + workflow_id + \"/executions/\"<br>\nTypeError: coercing to Unicode: need string or buffer, NoneType found<br>\n<br>\n>>> File `/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py` execution CRASHED. <<<<br>\n<br>\nTest statistics: Start time 2014-10-08 09:44:43 -- End time 2014-10-08 09:44:54 -- 11.15 sec.<br>\n<br>\n<<< END filename: `1001:/home/vmware/Pre-Deployment Verfication tests/Suite/Testcases/Compliance/vSphere//Test_verifyIpAddress.py` >>>', 'demo', 'demo', 'demo')` OK.
14-10-08 09:45:12  DEBUG    CeXmlRpc.py: 614: commit_to_database  CE: Saving to database was successful!

**Comment by bogdanpopescu** [comment]
@leanderc 
Code updated with latest changes, please verify if the issue is fixed.
