### ISSUE TITLE
Twister UI wont show

### ISSUE THREAD

**Issue by evopkay** [Luxoft/Twister#145]
@promihu @VasiliyS @dcioata @elenabratanova @bogdanpopescu 

Just an empty Blue page appears after accepting the java applet and signing in .
Not sure whats going on but this seems to be a persistent issue

**Comment by bogdanpopescu** [comment]
@evopkay 
Please let us know what OS are you using and what version on java.

**Comment by anuragamodi** [comment]
I have encountered the same problem and I found this was the browser issue for that OS, it automatically zoomed in the page just after signing in.
I tried using browser from another machine in the same network and there were no issues.
Possible steps to resolve:- Try closing and opening the browser.
or
Try removing the browser and re-installing it.
