### ISSUE TITLE
EP cannot be installed on Windows

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#15]
Twister User guide (pg3) states that EPs can also run on Windows.  When attempting to install a Twister Client using installer.py an AttributeError exception is thrown and the installation stops.

$ python installer.py
Traceback (most recent call last):
  File "installer.py", line 53, in <module>
    if os.getuid() != 0:
AttributeError: 'module' object has no attribute 'getuid'

**Comment by bogdanpopescu** [comment]
@CJHoffmann the user guide states now that Twister cannot be installed on Windows. There are only specific EPs that can be installed on Windows ( for Selenium, Sikuli, TestComplete )

**Comment by mtkuntz** [comment]
This issue can be Closed.
