### ISSUE TITLE
Tesbed - Device panel part is grayed out, jButtons are missing too

### ISSUE THREAD

**Issue by mmajdoubi** [Luxoft/Twister#151]
Hi,

I am using 3.040 release and all (applet) content is copied to www root directory. However the richtpanel of the testbed view is grayed out and it does not allow any changes, see the screenshot

![screen shot 2014-12-05 at 12 53 59 pm](https://cloud.githubusercontent.com/assets/846724/5315489/45d771e0-7c7e-11e4-98f7-a99a86ad137c.png)

Hope you can help to fix this issue

With Kind Regards
M.Majdoubi

**Comment by bogdanpopescu** [comment]
@mmajdoubi 
You need to reserve the testbed first. 
Try right-click on tb1 and reserve it. After that you can edit it's components.

Best regards,
Bogdan.

**Comment by mmajdoubi** [comment]
Thanks a lot for the tip, it's working now.
