### ISSUE TITLE
Projects are not listed in 'Scheduler' plugin

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#152]
Hi,

```
Could you please explain, how to set the project name in 'Scheduler' plugin? Looks like drop down has to list all projects so that we can choose one, but it isn't though got couple of projects.
```

![twister_scheduler](https://cloud.githubusercontent.com/assets/5869695/5362233/5abdcb46-7ff7-11e4-8e0d-754908f9e1f4.png)
is this a bug or am I missing something.

**Comment by bogdanpopescu** [comment]
@jashanka 
This is a bug, we'll fix it shortly.

**Comment by jashanka** [comment]
Now that the projects are being listed, I scheduled a run but after I add it nothing is getting listed in the table below, 

![image](https://cloud.githubusercontent.com/assets/5869695/5624638/ab858f34-958f-11e4-86a4-364eb734686c.png)

should this be a new bug? or could you please check it.

**Comment by Derrick-Liew** [comment]
Hi,

I downloaded the latest from branch "git_hub_branch", the bug is not fixed. Can you direct me to the latest fix? Thanks
