### ISSUE TITLE
Jira tab is not shown after activating the plugin

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#155]
Jira plugin tab is not shown after activating the plugin, screen shot below

![twister_jira_bug](https://cloud.githubusercontent.com/assets/5869695/5422385/a3826f26-82a4-11e4-8c13-c96077331b02.png)

Tried restarting both server and client, no luck!

**Comment by jashanka** [comment]
Greeting of the New Year 2015 Bogdan, Team and all Twister users :)

Bogdan, could you please mark the bugs as "ready to verify", so that I can test on new build, (if it's fixed)? Or is the fix still being given?

Thanks,
Jai

**Comment by bogdanpopescu** [comment]
Greetings @jashanka !
We delivered the  fix, please verify it.

**Comment by jashanka** [comment]
It's still not working :(  could you please check.

**Comment by jashanka** [comment]
Also when I try to remove Jira plugin from Local box, the GUI is getting scrambled as below,

![image](https://cloud.githubusercontent.com/assets/5869695/5624701/bad1297a-9590-11e4-82bd-c586f4df5369.png)

**Comment by jashanka** [comment]
Hi Bogdan,

```
Any update (or rather am I using correctly)?
```

**Comment by bogdanpopescu** [comment]
@jashanka 
we cannot reproduce this issue with the latest changes. Did you used the latest plugin from binaries/JiraPlugin/Jira directory ? If you used it and you still have the issue, please try the following:
1. Deactivate Jira plugin
2. Remove Jira plugin
3. logout from GUI
4. in your user home directory, edit file ~/twister/config/plugins.xml and remove the following section:

< Plugin >
< name > JIRA < /name >
< jarfile>JiraPlugin.jar< /jarfile >
< pyfile>JiraPlugin.py< /pyfile >
< status>disabled< /status >
< property >
< propname >jiraserver< /propname >
< propvalue/ >
< /property >
< /Plugin > 
1. Login back in Twister GUI
2. download Jira plugin
3. Activate Jira plugin.

Let me know what happens

**Comment by jashanka** [comment]
I'm not able to remove Jira Plugin, I get the following screen when I click the remove button and again when I login back I see Jira is already downloaded. 

![image](https://cloud.githubusercontent.com/assets/5869695/5726567/32477c7c-9b11-11e4-99fe-6aabf09eaecc.png)

**Comment by jashanka** [comment]
Can you also please comment on plugin bugs 152 and 149, I tried many times for these plugins, no new update than I've given already. Also is this some how related to java version in the browser? (I'm using jre-7u13-windows-i586).

**Comment by bogdanpopescu** [comment]
@jashanka 
I think is the same issue for 152 and 149, so let's fix this one first. I suppose you are launching the web browser on a Windows machine. If so, try this:
1. close the browser
2. on Win machine, go to user directory ( e.g. on Win7 , C;\Users< your_user > ) and you'll find there a directory called .twister . Remove this directory.
3. Open the browser, connect to Twister server and try to download and activate Jira plugin.

**Comment by jashanka** [comment]
Thanks Bogdan, I'm able successfully able to see Jira tab and main page. Just wanted to connect to Jira server so I logged in and gave my credentials but in the drop downs of 'project', 'version' and 'components' nothing is listed except 'select project', 'select version' and 'select coponent'.

This is the content of plugin.xml in my home dir for Jira,

<Plugin>
<name>JIRA</name>
<jarfile>JiraPlugin.jar</jarfile>
<pyfile>JiraPlugin.py</pyfile>
<status>enabled</status>
<property>
<propname>jiraserver</propname>
<propvalue/>
</property>
</Plugin>

Is this file is correct? 
(Also I suspect it's not really logging into the server but going directly to second page)

Thanks again for your continued support.

**Comment by bogdanpopescu** [comment]
@jashanka 
Did you copy JiraPlugin.py in /opt/twister/plugins ? 
This file can be found in twister repository in binaries/JiraPlugin/Jira directory.

**Comment by jashanka** [comment]
Yes I did.
From the latest version I copied everything from binaries/JiraPlugin//Jira/\* to /opt/twister/plugins

**Comment by bogdanpopescu** [comment]
check /opt/twister/server_log.log if there are any error messages when you try to connect to Jira server.

**Comment by jashanka** [comment]
Following are the errors I'm getting when I try to login with Jira credentials.

---

15-01-14 04:43:50  WARNING  xmlparser.py: 1241: getPlugins  User jai: PluginParser ERROR: Unhandled exception in plugin file `JiraPlugin`! Exception: No module named suds.client!
15-01-14 04:43:50  ERROR    CeProject.py: 2968: _build_plugin  Plug-ins: Cannot find plug-in name `JIRA`!
15-01-14 04:43:50  ERROR    CeXmlRpc.py: 1345: run_plugin  _ERROR_ Plugin `JIRA` does not exist for user `jai`!

---

**Comment by bogdanpopescu** [comment]
you need to install python suds package.

**Comment by jashanka** [comment]
Just installed suds package and tired, please see error below. I see it's trying to connect to database as well 

---

15-01-14 04:47:09  WARNING  xmlparser.py: 1241: getPlugins  User jai: PluginParser ERROR: Unhandled exception in plugin file `JiraPlugin`! Exception: No module named suds.client!
15-01-14 04:47:09  ERROR    CeProject.py: 2968: _build_plugin  Plug-ins: Cannot find plug-in name `JIRA`!
15-01-14 04:47:09  ERROR    CeXmlRpc.py: 1345: run_plugin  _ERROR_ Plugin `JIRA` does not exist for user `jai`!
Attempting to connect to the server: PRINTING_MY_JIRA_SERVER_NAME
Failed to connect to: PRINTING_MY_JIRA_SERVER_NAME
15-01-14 04:54:29  ERROR    CeDatabase.py: 125: connect_db  MySQL error for user `jai`: `1045 - Access denied for user 'user'@'localhost' (using password: NO)`!
Attempting to connect to the server: PRINTING_MY_JIRA_SERVER_NAME
Failed to connect to: PRINTING_MY_JIRA_SERVER_NAME

---

still it says suds.client isn't found!

**Comment by jashanka** [comment]
I did a server and client restart, here is the latest server log,

Please note that, some additional line (rpc/soap/jirasoapservice-v2?wsdl) is appended with jira server than what I've given, so it's not able to connect

---

Attempting to connect to the server: PRINTING_MY_JIRA_SERVER_NAME/rpc/soap/jirasoapservice-v2?wsdl
Failed to connect to: PRINTING_MY_JIRA_SERVER_NAME/rpc/soap/jirasoapservice-v2?wsdl

---

**Comment by jashanka** [comment]
Here is where it's appending to server name,

twister/plugins/JiraPlugin.py

---

```
 67             if 'server' not in args.keys():
 68                 logger.debug("inside if")
 69                 jira_env['server'] = "http://localhost:8080"
 70                 logger.debug("Server was not provided, using local server as default")
 71             else:
 72                 logger.debug("inside else")
 73                 jira_env['server'] = args['server']
 74                 jira_env['server'] = jira_env['server'] + "/rpc/soap/jirasoapservice-v2?wsdl"
```

---

whats the significance of appending this to the 'jira server' name? ( I tried removing it as well, still same problem).
