### ISSUE TITLE
Unable to find/run shell script referenced by a Perl script 

### ISSUE THREAD

**Issue by mmajdoubi** [Luxoft/Twister#157]
I am trying to execute a Perl script, this Perl script (fragmentation_analyzer.plx) has reference to another shell script named pcap_path.sh. Both scripts a located in the same directory:
![screen shot 2014-12-17 at 11 44 10 am](https://cloud.githubusercontent.com/assets/846724/5469984/c9478dd6-85e2-11e4-9676-89a0faf257fe.png)

After executing the Perl script, an error is generated about the shell script reference. Twister is not able the open/find the shell script referenced by the Perl script, see below for the logging

![screen shot 2014-12-17 at 11 49 04 am](https://cloud.githubusercontent.com/assets/846724/5469987/cfca0e86-85e2-11e4-873f-cdc1130e9336.png)

Is Twister able to find any referenced scripts located in the same (root) directory? 

Thanks in advance
M.Majdoubi

**Comment by bogdanpopescu** [comment]
@mmajdoubi 
If you use the absoulte path, it should work. 
Twister client has different environment, this is design intent.
Another option would be to define a global variable in GUI ( Configuration->Global Parameters ) to hold the path to your reference and use it to access the reference.

**Comment by mmajdoubi** [comment]
ok Thanks
