### ISSUE TITLE
Report generation issue: Shared DB XML Error

### ISSUE THREAD

**Issue by mmajdoubi** [Luxoft/Twister#158]
Hi 
I updated Twister to the latest release of yesterday, a new functionality is added  to this release (Shared DB XML).
Unfortunately the reporting tab is not working anymore,a share DB XML error is generated after clicking the reports tab:

14-12-19 13:37:42  INFO     [19/Dec/2014:13:37:42] HTTP 
Request Headers:
  AUTHORIZATION: Basic dXNlcjpwYXNzd29yZA==
  REFERER: http://10.17.130.50/twister/
  HOST: 10.17.130.50:8000
  CONNECTION: keep-alive
  Remote-Addr: 10.17.130.110
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0
  COOKIE: session_id=45a652e7479435b015895c1de3b846080c1edcae
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
14-12-19 13:37:42  ERROR    [19/Dec/2014:13:37:42] HTTP Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/twister/server/CeReports.py", line 152, in index
    self.load_config(usr, True)
  File "/opt/twister/server/CeReports.py", line 109, in load_config
    report_queries = DBParser(usr, db_file, shared_db_path).get_reports(db_cfg_role)
  File "/opt/twister/common/xmlparser.py", line 1139, in get_reports
    raise Exception('Invalid shared DB XML!')
Exception: Invalid shared DB XML!

The GUI is also changed, shared DB  is added in the DB pane but is grayed out !. 

![screen shot 2014-12-19 at 2 23 57 pm](https://cloud.githubusercontent.com/assets/846724/5504926/e56046bc-878a-11e4-9593-e1ebefc449aa.png)

The content of the DB xml files is listed below:

![screen shot 2014-12-19 at 2 24 29 pm](https://cloud.githubusercontent.com/assets/846724/5504989/e1ec0948-878b-11e4-9e0d-b56c5466440d.png)
![screen shot 2014-12-19 at 2 23 41 pm](https://cloud.githubusercontent.com/assets/846724/5504994/f477dad8-878b-11e4-9f99-ba7f306b5cd1.png)

What is the purpose of using shared DB setup and how to fix the issue listed above?

Thanks in advance

With kind regards
M.Majdoubi

**Comment by croqaz** [comment]
Hello @mmajdoubi,

Shared DB is a new feature that allows more users to have the same reports, or insert the results of the tests in the same database. It's mandatory to provide the path for shared DB, even if the file contains no insert queries, or no report section.
_The default file from repository, from `config/shared_db.xml` is just fine_ :smile: 

The print screen with your shared DB is ok, the file is valid, BUT the path to the shared DB has to be provided in the file `/opt/twister/config/users_and_groups.ini` ;
make sure the section `shared_db_cfg = /opt/twister/config/shared_db.xml` is **not** commented !

Hope this helps.

**Comment by mmajdoubi** [comment]
I just tried your suggestion and it works indeed, thanks a lot for your help!
