### ISSUE TITLE
Database error. 

### ISSUE THREAD

**Issue by mandarkallol** [Luxoft/Twister#16]
I have installed it succesfully, getting twister framework correctly. 
## "Project" and "Configurations" tabs are working fine. But when I click on "Reports -> Details" or "Reports -> History" tabs I am getting this error. Please let me know how to create these databases. 

Details
Error in query `SELECT * FROM results ORDER BY id`!

**Comment by ajaykools** [comment]
Even I'm facing the same issue.
After running few script i want to check 'History' and Details of it but it is throwing is Database error exactly like above mentioned.

<b>It would be very useful if you add simple sql dump in this package. <i>"twister.sql"</i></b>

**Comment by bogdanpopescu** [comment]
Ok, first create the database. You can change it's name to whatever you want. To do that, login to mysql server and issue the command:
create database foo; // change foo to whatever name you want
Now, it's time to create the table. Use the following command:

create table results ( id int(10) unsigned not null auto_increment primary key, 
run_nr int (10), workstation varchar(32),  suite varchar(32), test_name varchar (32),
datetime_started varchar(32), datetime_finished varchar(32), status varchar(10) engine MyISAM;

Now, let's create the user:
create user 'user'@'localhost' identified by 'password';

and let's grant permissions:
 grant all on _._ to 'user'@'localhost';
flush privileges;

That should be all with the db schema that you have in db.xml

**Comment by bogdanpopescu** [comment]
Database schema provided in installer/packages/twister_demo.sql
