### ISSUE TITLE
Invoking EP on a remote machine

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#162]
Hi,

```
While trying to invoke EP from a remote machine getting the following error
```

![image](https://cloud.githubusercontent.com/assets/5869695/5758148/90d7b010-9c77-11e4-9952-24ad8c01d588.png)

These are the steps I followed (based on user guide '14.20 EP start-up')
1. I've a twister server and client installed on server 'A' and on server 'B' (also SUT) I've my TC's to run (on server 'B' itself).
2. I installed only twister client on 'B' and modified the twister/epname.ini as below,

[myEP]
CE_IP   = server 'A' address
CE_PORT = 8000
1. started twister client from 'B' and started twister server from 'A'. 
2. Now in the GUI, I'm able to associate the 'myEP' to SUT, but when I try running a test getting the above error.

Also please note that in GUI's logs section, I don't see remote EP but it's showing local EP.
And is there a way to list TC's present in 'B' in GUI (I tried changing the path from GUI, but it lists only local machine dirs)
Hopefully I've explained the problem properly, please revert if it isn't clear.

**Comment by bogdanpopescu** [comment]
Probably the client on machine B didn't registered to server A. When a client registers to server, you should see a message in server_log.log similar with the following:

15-01-15 16:06:54  INFO     CeRpyc.py: 833: register_eps  Registered client manager for user `bogdan`  -> Client from `11.126.32.20:34235` ++ ['tsc-openflow_EP-1001', 'tsc-openflow_EP-1002'].

The TC's must be on server machine ( A ), no need to have TC's on client machines. A solution for you would be to mount them on server A using NFS.

**Comment by jashanka** [comment]
Oh yes, now it's running without any change, you're right Sir, may be the client register was the issue. Thank you.

Before I close, small calrification,
When TC's are in machine (A) and if I run them using remote EP of machine (B), does the script run on machine (B) ? I guess Yes.

**Comment by bogdanpopescu** [comment]
Yes, the script runs at client machine, it is transferred from server to client machine automatically.

**Comment by jashanka** [comment]
Wow that's really nice.
Thank you Bogdan,
