### ISSUE TITLE
tc_log hyperlink reference is missing 

### ISSUE THREAD

**Issue by mmajdoubi** [Luxoft/Twister#163]
The tc_log column in the reporting page does not contain the hyperlink to the test logs, a snapshot of the page is included below.  It was working before but sinds the last upgrade it does not work any more, is there any code made in the last release or do I have to enable the hyperlink specifically?

Thanks in advance

![screen shot 2015-01-15 at 14 46 49](https://cloud.githubusercontent.com/assets/846724/5758411/bf804c26-9cc5-11e4-8528-f244d023050e.png)

**Comment by croqaz** [comment]
Hello,
This is a known issue from the last update.
It will be fixed in the next batch. Until then, if you want, you can edit the server/CeDatabase.py file and replace all `conn.escape_string`  with  `MySQLdb.escape_string`.

**Comment by bogdanpopescu** [comment]
@mmajdoubi 
Hi, do you plan to verify this ?
