### ISSUE TITLE
Shared DB is not editable from GUI

### ISSUE THREAD

**Issue by jashanka** [Luxoft/Twister#165]
When Shared DB is selected from GUI, it's fields are not editable,
![image](https://cloud.githubusercontent.com/assets/5869695/5789047/5604ed56-9e0f-11e4-8663-1bac66ca025d.png)

or is it that, we've to only edit it manually?

**Comment by bogdanpopescu** [comment]
This is design intent. Shared DB details must be edited only by the Twister administrator so there is no point for the user to modify the shared DB.

**Comment by jashanka** [comment]
Makes sense, Thanks Bogdan.
PS: Could you also please take a look on my Plugin bugs, I'm really kind of stuck using them.
