### ISSUE TITLE
Twister execution web page (twister server) was not showing “run” button for ‘user1’ whereas showing “run” button for other users

### ISSUE THREAD

**Issue by neeraj8186** [Luxoft/Twister#167]
Twister execution webpage  issues – 
• No. of users – user1, user2, user3 and user4  
• User ‘user1’ – facing issues w.r.t starting the test as “run” button disabled. 
         - Message that comes while mouse rollover on “run” button shows – “stop CE to run”
    - Triages -
               \* While restarting the client service from user1, “run” button was visible only for 3-4 seconds.
               \* We tried killing all processes associated with user1 on twister server, did not work out. 
               \* Tried removing twister server’s user – user1 and adding back to the userlist, did not work. 
               \* Final call made through restarting server services which terminated all the user activities 
•     For rest of the users “run” button was visible and thus able to run test properly. 

Please let us know the process/workaround for such kind of issues.

**Comment by bogdanpopescu** [comment]
@neeraj8186 
Sorry, I don not understand the issue. Website = java applet ?
Do you have multiple users connected in the same time ?
