### ISSUE TITLE
Directory Choices must come from http host not local browser

### ISSUE THREAD

**Issue by JimCamp** [Luxoft/Twister#17]
When selecting configuration files they must be from the http server location not the browser location. We have different paths on different machines to the files. Users need to be able to use a Win7 PC for all browser functions while the server can remain on linux.

**Comment by bogdanpopescu** [comment]
@JimCamp the configuration files come from server location. What configuration file are you referring ?

**Comment by JimCamp** [comment]
If I use browser on PC to HTTP server on Linux. When trying to change configuration directories the dialogue box does not come up and explorer freezes. I believe that this is due to local vs remote file selection mechanisms. Maybe the selection dialogue is just not available on the windows explorer. This is on version 2.003.
Thanks
Jim Campbell

**Comment by notbraveulysses** [comment]
we are using nis on the linux boxes in richardson - the server and client config files are the same.

**Comment by bogdanpopescu** [comment]
Confirmation received from JimCamp that issue is fixed.
Closing issue.
