### ISSUE TITLE
Cannot connect to MySql server  

### ISSUE THREAD

**Issue by ravichandra66** [Luxoft/Twister#170]
I have given the full  admin perimisson for user and  i have flowing issue with  reports 
1. Cannot connect to MySql server `localhost / twister_demo` !  when click the report for twister applest  
2. Reports  button not working  after the login in to twister home  if user have admin permisssion 
   test excution and user managemnt page are loading and but reports page .

**Comment by divyayadav** [comment]
Even I face similar issue, I am able to connect to mysql using command line.
But with twister I am getting this error,
15-05-29 10:15:17  INFO     CeXmlRpc.py: 626: test_database  Failed to connect to MySQL User connection `user @ localhost / twister_demo`, for user `user`: MySQL error `(1045, "Access denied for user 'user'@'localhost' (using password: NO)")`!

**Comment by bogdanpopescu** [comment]
@divyayadav 
Hi,

Please go in Configuration->Database section, set the correct user and password and press "Test connection" button. If the connection is succesfull, save the configuration ( press Save button in the same window ).

![save_db](https://cloud.githubusercontent.com/assets/1727668/7931690/67eb8c1a-091b-11e5-850a-e9686b61f9a4.png)

**Comment by divyayadav** [comment]
Thanks, but the issues is a lot of UI is disabled throughout the twister web interface. Even Run button for scripts is disabled.
Followed the twsiter guide on Ubuntu 12.04.05,

![screenshot from 2015-06-03 15 25 33](https://cloud.githubusercontent.com/assets/7946807/7973841/0b12cedc-0a0f-11e5-8c47-86164d1752e1.png)
