### ISSUE TITLE
Unable to login to the Twister application : CE is not running, please start CE in order for Twister Framework to run properly

### ISSUE THREAD

**Issue by sravanmedarapu** [Luxoft/Twister#172]
Hi There,

We are trying to install the Twister framework on Ubuntu 12.04,  but we are seeing some errors while logging in to the twister application. 

We are able to install  the Framework successfully and we ran the twister server and client from below respective locations as well.

```
  ->  Start Twister server form the path:  /opt/twister/bin/start_server 
  ->  Start Twister client  from the path: home/user/twister/bin; ./start_client start
```

But while logging in to the application ( http://localhost/twister), we are getting the error message as “CE is not running, please start CE in order for Twister Framework to run properly” and  we are seeing the error message while starting the server saying “import \*  File "/opt/twister/common/helpers.py", line 41, in <module>    from Crypto.Protocol.KDF import PBKDF2 ImportError: No module named KDF” but it was installed .

Few More details regarding our installation environment :

 Installed framework in UBUNTU 12.04 
 Python 2.7.3 version
 Oracle Java 1.7 version
 Apahce2 installed
 Mysql DB

And we also tried in Ubuntu 13.10 version as well we are seeing the same error message. 

Can any one please give me some suggestion on this.

**Comment by croqaz** [comment]
Hello @sravanmedarapu 

`from Crypto.Protocol.KDF import PBKDF2` error appears only if you have an older version of Python Crypto (2.5 or less).

Please open a Python terminal and type:
`
import Crypto

print Crypto.version_info
`

What's the output ?
It should be `(2, 6, 1, 'final', 0)`

**Comment by rsavalagi** [comment]
This issues has not been resolved, i am using the right version of crypto can you please help

> > > import Crypto
> > > print Crypto.version_info
> > > (2, 6, 1, 'final', 0)
