### ISSUE TITLE
twsiter excution is crashed 

### ISSUE THREAD

**Issue by ravichandra66** [Luxoft/Twister#173]
Please find the error log 

TWISTER_PATH is set to `/home/user/twister`.

EP Info: Connecting to the Central Engine...
EP Debug: Connected and authenticated to CE at `10.201.10.64:8000`.

EP Debug: Creating a threaded logger...
EP Debug: Created the logger.

~ Start the Execution Process ~
~ User: user ; EP: controller_EP-1001 ; CE path: 10.201.10.64:8000 ~

Downloading library `TscCommonLib.py` ...
... all libraries downloaded.

EP Info: Start running the tests!

===== ===== ===== ===== =====
 Starting suite `101 - S1`
===== ===== ===== ===== =====

Downloading library `TscFtpLib.py` ...
Downloading library `TscSshLib.py` ...
Downloading library `TscStepLib.py` ...
Downloading library `TscTelnetLib.py` ...
Downloading library `TscThreadsLib.py` ...
Downloading library `TscUnitTestLib.py` ...
Downloading library `newoftest/lib/case_one.py` ...
Downloading library `newoftest/lib/common.py` ...
Downloading library `newoftest/lib/dpctl.py` ...
Downloading library `newoftest/lib/of_one.py` ...
Downloading library `newoftest/lib/ofctl.py` ...
Downloading library `newoftest/lib/ovs_config.py` ...
Downloading library `newoftest/lib/sshtestcase.py` ...
Downloading library `newoftest/lib/tw_of_one.py` ...
Downloading library `newoftest/lib/vsctl.py` ...
Flatten `newoftest/lib/case_one.py`.
Flatten `newoftest/lib/sshtestcase.py`.
Flatten `newoftest/lib/vsctl.py`.
Flatten `newoftest/lib/tw_of_one.py`.
Flatten `newoftest/lib/common.py`.
Flatten `newoftest/lib/ofctl.py`.
Flatten `newoftest/lib/ovs_config.py`.
Flatten `newoftest/lib/of_one.py`.
Flatten `newoftest/lib/dpctl.py`.

<<< START filename: `1001:/home/user/oftest//newoftest/lib/tw_of_one.py` >>>

Test case exception:
File "/home/user/twister/client/executionprocess/ExecutionProcess.py", line 1178, in tests
    result = current_runner._eval(str_to_execute, globs, args)
  File "/home/user/twister/client/executionprocess/RunnerClasses.py", line 253, in _eval
    execfile(fpath, globs_copy)
  File "/home/user/twister/.twister_cache/controller_EP-1001/tw_of_one.py", line 9, in <module>
    from  common import MYSSHClient
ImportError: cannot import name MYSSHClient

> > > File `/home/user/oftest//newoftest/lib/tw_of_one.py` execution CRASHED. <<<

Test statistics: Start time 2015-02-26 14:54:46 -- End time 2015-02-26 14:54:46 -- 0.09 sec.

<<< END filename: `1001:/home/user/oftest//newoftest/lib/tw_of_one.py` >>>
# 
# . . . All tests done . . .

**Comment by croqaz** [comment]
Hello @ravichandra66 ,

The error is `ImportError: cannot import name MYSSHClient`.
You don't have the file `MYSSHClient` in the libraries.

The tests are run in a separated environment, where you cannot easily access other system files.
Why don't you use `MYSSHClient` file in your libraries list ?

**Comment by ravichandra66** [comment]
MYSSHClient libraries loated the in   newoftest/lib/common.py.

Please find attahment of 
![image](https://cloud.githubusercontent.com/assets/10512952/6390301/064799da-bdd1-11e4-83d6-530932a17b50.png)

![image](https://cloud.githubusercontent.com/assets/10512952/6390308/1b7a3c22-bdd1-11e4-8922-8c3fc956237e.png)

**Comment by ravichandra66** [comment]
i am getting error like 

_ERROR_ Cannot import the Common libraries! `cannot import name iniparser`

**Comment by croqaz** [comment]
Hello @ravichandra66

This is a rare issue that you are having; you have created a library called "common" that is in conflict with Twisters "common" library that is absolutely essential for running tests.
Try to rename common.py to common1.py.
