### ISSUE TITLE
Run button disabled

### ISSUE THREAD

**Issue by bsikandar** [Luxoft/Twister#176]
Hi,

I was unable to stop the run went and killed the following process.

*****7425     1  2 Aug03 ?        00:50:45 /usr/bin/python -u /home/twister/client/executionprocess/ExecutionProcess.py -u abcd -e abcd-_EP-1001 -s 127.0.0.1:8000

Now i see an issue, as i cannot start a run . Run button disable, when i move my mouse over this button it shows Stop CE to enable.

... all libraries downloaded.

EP Info: Waiting for the EP to start...

Still waiting for the start signal...

My question:
If i restart the twister server service problem gets resolved. But how do i solve this issue without restarting the server side engine.

**Comment by bogdanpopescu** [comment]
@bsikandar 
Hi,
We do not recommend killing the ExecutionProcess, but using start_client restart command.
Anyway, we just submited a fix for this issue. Please verify.
Basically, if you will restart the client using ./start_client restart command, it should clear the issue.

**Comment by bsikandar** [comment]
Thank you Bogdon,

Appreciate your support, we will give a try with this fix.
