### ISSUE TITLE
Cannot add components to testbed, cannot add any properties or even edit existing properties

### ISSUE THREAD

**Issue by dlal66** [Luxoft/Twister#177]
I just downloaded the latest twister code and it installed fine. I am having issues doing anything on the testbed configuration page. I can add a TB but after that the screens on the right are grayed out and I am unable to add anything. For exiting TB's I can see some properties (e.g IP) but cannot edit them

**Comment by bogdanpopescu** [comment]
@dlal66 
Hi,

You have to reserve the test bed before adding/editing the components. 
Right-click on the test bed and select Reserve. After this, you should be able to edit it.

**Comment by dlal66** [comment]
Thanks a lot. I do not believe this is mentioned in the user manual.
Follow-up question: How can I set the EP? After defining my testbed (devices, IP addresses) I'd like to define a SUT. On the bottom half of the screen it say "SET EP" in addittion to some other options. They are all Greyed out. I tried "Locking" the SUT but that does nothing.

Thanks .

**Comment by bogdanpopescu** [comment]
@dlal66 
Hi,

You should follow these steps:
1. Go to Configuration->System Under test
2. Select User or Global ( User is recommended for the begining to avoid issues with file permissions )
3. Press New button  and name your SUT
4. Select the new SUT and press Oen button
5. Now you can use Set EP button on the bellow window ( you need to have the client started to be able to see the configured EP's ).
6. Save the changes

I hope this helps

**Comment by dlal66** [comment]
Thank you!

**Comment by dlal66** [comment]
I have started playing the platform and am hitting some road blocks. I am using perl and am not sure how to access the properties of a resource. I am able to use get_resource() to get the resource and printing it in perl displays {'meta":xxx, 'ip' : 192.168.0.1'}. How do I get access to the 'ip' property value?

Are there any resources that explain the usage is perl?

Thanks

**Comment by dlal66** [comment]
Please ignore the previous question. I can simply use string operation to retrieve the value.
