### ISSUE TITLE
Need to use Twister Framework via cli 

### ISSUE THREAD

**Issue by neeraj8186** [Luxoft/Twister#180]
Hi Team,

I need to run my test utilising Twister framework via cli. Basically like leverage use of cli.py placed under /opt/twister/bin. 
Please guide me how i can do that.

Regards,
Neeraj Sharma

**Comment by bogdanpopescu** [comment]
@neeraj8186 
The usage is described in User Guide so please check there.
A quick example on how to start a project run from CLI:
python cli.py --server my_server:8000 -–login usr:passwd -c ~/twister/config/fwmconfig.xml -p ~/twister/config/testsuites.xml -s start
