### ISSUE TITLE
Unable to queue test case - queued test case status becomes notexec

### ISSUE THREAD

**Issue by nitinaran** [Luxoft/Twister#181]
Below is what I am trying to do:
1. Run a suite "SuiteTest01" using cli.py (./cli.py --login=<username>:<password> -s start -c <absolute path to the fwmconfig.xml file> -p <absolute path to the project xml file>)
2. Once its started, I am trying to run the following command to queue a test case to the suite: ./cli.py --login=<username>:<password> -q SuiteTest01:<path to the test case file>
3. The result of the command is successful, and it actually queues the test case, however, the queued test case is never executed. Below is the output of the details command:

Your Suites are:
- on ubuntu14-x64_EP-1001 :
  - (id 101) SuiteTest01
    - [pass] (id 1001) /home/naran/twister/testsuites//testing/test01.py
    - [notexec] (id 1002) /home/naran/twister/testsuites/testing/test02.py

I tried with running the original suite from the GUI even, and queuing using cli.py, but the queued test case is never executed.

**Comment by bogdanpopescu** [comment]
@nitinaran 
Hi, the issue is fixed and delivered. Please verify it.

**Comment by nitinaran** [comment]
Working well with the latest version. Thank you very much. Much appreciated.
