### ISSUE TITLE
Disabled “run” button for ‘user1’ whereas enabled “run” button for other users

### ISSUE THREAD

**Issue by Hamza989** [Luxoft/Twister#183]
Disabled “run” button for ‘user1’ whereas enabled “run” button for other users

**Comment by bogdanpopescu** [comment]
@Hamza989 
This is related to issue #182

**Comment by Hamza989** [comment]
Verified with v.3.067 version of twister , Run button enabled for all user.
It might be because user has forcefully must have killed background process by using kill -9 command, which has Disabled run button .
