### ISSUE TITLE
v3.067: Multiple SUTs in single projects fail to start subsequent Suite

### ISSUE THREAD

**Issue by meetashutosh** [Luxoft/Twister#184]
On moving from v3.057 to v3.067, we are finding that if project has multiple Suites the twister executes only Suite1.
1. Consider Suite1 and Suite2 as shown below:
   ![image](https://cloud.githubusercontent.com/assets/10251311/11741609/17cf13f4-a020-11e5-952d-219971bc6874.png)
2. On executing Run, twister starts only the Suite1 and not Suite2. Twister v3.067 has to execute the selected test from Suite2.
   ![image](https://cloud.githubusercontent.com/assets/10251311/11741523/a66591a2-a01f-11e5-99e9-c9849f9f122e.png)
3. Twister v3.067 fails to find that nothing is selected from Suite1 which it executed.
   ![image](https://cloud.githubusercontent.com/assets/10251311/11741544/c277dabc-a01f-11e5-823f-5b154d18a284.png)

Kindly provide a fix as this fails testing multiple suites from a project.

**Comment by bogdanpopescu** [comment]
@meetashutosh 
Code changes delivered, please verify it.

**Comment by meetashutosh** [comment]
@bogdanpopescu 
Thank you.
The issue is fixed now.
