### ISSUE TITLE
mysql setup

### ISSUE THREAD

**Issue by notbraveulysses** [Luxoft/Twister#19]
please include some basic commands to get started with a mysql server

create database interop;
use interop;
create table results ( id int(10) unsigned not null auto_increment primary key, run_nr int (10), workstation varchar(32), suite varchar(32), test_name varchar (32), datetime_started varchar(32), datetime_finished varchar(32), status varchar(10)) engine=myisam;

create user 'user'@'localhost' identified by 'password';
grant all on _._ to 'user'@'localhost' identified by 'password';

select user,host,password from mysql.user;

show columns from interop.results;

**Comment by bogdanpopescu** [comment]
Database schema provided in installer/packages/twister_demo.sql
