### ISSUE TITLE
Once the server logs are deleted, they aren't recreated automatically when the testsuites/scripts are run from twister GUI

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#21]
Once the server logs are deleted, they aren't recreated automatically when the testsuites/scripts are run from twister GUI
/opt/twister/server_logs.log
/opt/twister/logs/*

Restart twister: Doesn't create the logs even now
Only after restarting the server, the logs get re-created

**Comment by bogdanpopescu** [comment]
This is intended behavior. The logs are crated and written by the central engine ( server )

**Comment by sandhyamisra** [comment]
Can be closed.
