### ISSUE TITLE
Save button is shown instead of Open button in pre/post execution open file dialog

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#23]
Instead of open button save button is shown while selecting pre and post execution files from the open file dialog box.
Also, the file location is always the home directory. It doesn't remember the last visited location or doesn't open the 

path which is present in the text box. For example: If the pre-execution script contains: 

/home/user/twister/demo/testsuite-python/init.py, I would ideally expect it to take me to the 

/home/user/twister/demo/testsuite-python/ directory instead of /home/user/
![prepostexecution-openbutton](https://f.cloud.github.com/assets/4291567/761135/19bf0a04-e7c5-11e2-80a9-54c60120455d.JPG)

**Comment by bogdanpopescu** [comment]
@sandhyamisra  Please verify with the latest code changes
