### ISSUE TITLE
when start_ep.py is run it should not throw an error for already running eps instead they can be shown as info/warning

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#25]
user@user-VirtualBox:~/twister/bin$ sudo python start_ep.py
Found `6` EPs: `EP-1001, EP-1002, EP-1003, EP-1004, EP-1005, EP-1006`.
Error: Process EP-1001 is already started for user user! (ping=3 sec) 
[should be changed to " info " or "warning" message instead of "error" message]

Will execute: nohup /usr/bin/python -u /home/user/twister/client/executionprocess/ExecutionProcess.py user EP-1002 "127.0.0.1:8000" eth0 > "/home/user/twister/.twister_cache/EP-1002_LIVE.log" &
Ok! `EP-1002` for user `user` launched in background!

**Comment by bogdanpopescu** [comment]
This behavior was changed by automatic start of execution engines. The start_ep script was removed from repository.
