### ISSUE TITLE
When a new EP is added to the list of epname.ini, and run the start_ep.py and checked ./cli.py --eps doesn't list the newly added ep

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#26]
Added new EP called "EP-1006" in epname.ini file and restarted client [ie, start_ep.py]

Now check ./cli.py --eps
user@user-VirtualBox:~/twister/bin$ python cli.py --eps
Hello, user `user`.
Your Execution-Processes are:
EP-1001 : running (last active 5 sec)
EP-1002 : running (last active 5 sec)
EP-1003 : service not running
EP-1004 : service not running
EP-1005 : service not running

The added "EP-1006" is not listed in the output. 
Now restarted the server[ie,  "start_server"] . Only after retstarting the central Engine [server] , "EP-1006" is reflected in the output. If User is adding an EP in their epname.ini file then it should be reflected in the eps list once the client is restarted. But system is expecting the server to be restarted to show the newly added ep in the ep's list.

**Comment by bogdanpopescu** [comment]
@sandhyamisra  this was fixed on 12th July. The start_ep was replaced with start_client script. Please verify it.

**Comment by sandhyamisra** [comment]
The newly added EP is now being listed when cli.py --eps is run however all the EPs are shown as inactive

user@user-VirtualBox:~/twister/bin$ python cli.py --eps

Hello, user `user`.

Your Execution-Processes are:
EP-1001 : service not running
EP-1002 : service not running
EP-1003 : service not running
EP-1004 : service not running
EP-1005 : service not running
EP-1006 : service not running
EP-1007 : service not running

user@user-VirtualBox:~/twister/bin$ cat ../config/epname.ini 

# Each section must be the name of an Execution Process.

# The name of an Execution Processes MUST be UNIQUE !

# The IP and PORT will be used by each EP, to connect to Central Engine.

# Enabled = 1, means that the EP will be started, when executing

# ./start_ep.py, from twister/bin folder.

# For sniffer configuration ENABLED = 1 means that the sniffer will start,

# when executing ./start_ep.py, from twister/bin folder and ETH_INTERFACE = eth0

# reffers to sniffer ethernet interface.

[PACKETSNIFFERPLUGIN]
ENABLED            =    1
ETH_INTERFACE    =    eth0

[EP-1001]
CE_IP    =    127.0.0.1
CE_PORT    =    8000
ENABLED    =    1

[EP-1002]
CE_IP    =    127.0.0.1
CE_PORT    =    8000
ENABLED    =    0    

[EP-1003]
CE_IP    =    127.0.0.1
CE_PORT    =    8000
ENABLED    =    0

[EP-1004]
CE_IP    =    127.0.0.1
CE_PORT    =    8000
ENABLED    =    0

[EP-1005]
CE_IP    =    127.0.0.1
CE_PORT    =    8000
ENABLED    =    0

[EP-1006]
CE_IP   =       127.0.0.1
CE_PORT =       8000
ENABLED =       1 

[EP-1007]
CE_IP   =       127.0.0.1
CE_PORT =       8000
ENABLED =       1 
user@user-VirtualBox:~/twister/bin$

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
The EP's are started on demand because we changed the mechanism on how to start EP's for the automatic start feature. If no test case is executed, the EP's will be in idle state. The state changes when test cases are executed.

**Comment by sandhyamisra** [comment]
I understand that the EP state change when the scripts are run but it would be nice if the cli.py --eps reflects the state as Enabled when epstate.ini sets the flag as 1 and Disabled when it is set as 0 and when the script runs it can be shown as Running.

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
There is no ENABLED flag anymore. The User Guide was updated, please check section 4 where epname.ini file structure is described.

**Comment by sandhyamisra** [comment]
Ok this can be closed
