### ISSUE TITLE
Unable to queue files in the test suite through cli

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#27]
user@user-VirtualBox:~/twister/bin$ ./cli.py --queue /home/user/twister/config/users/MYTEST2.XML:/home/user/twister/demo/testsuite-python/init.py

Hello, user `user`.
Failed to queue test `/home/user/twister/demo/testsuite-python/init.py` was queued in suite `/home/user/twister/config/users/MYTEST2.XML`!

**Comment by sandhyamisra** [comment]
Also, unable to view the details using --details option  for cli

user@user-VirtualBox:~/twister/bin$ python cli.py –details

Hello, user `user`.

User status : stopped
Last started: 2013-07-05 09:54:19
Time elapsed: 0

Your Suites are:
- on EP-1001 :
  - nothing here
- on EP-1002 :
  - nothing here
- on EP-1003 :
  - EXAMPLE
    Traceback (most recent call last):
    File "cli.py", line 275, in <module>
    checkDetails(proxy, user, opt)
    File "cli.py", line 169, in checkDetails
    fname = proxy.getFileVariable(user, f_id, 'file')
    File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
    File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
    File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
    File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
    File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
    File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
    xmlrpclib.Fault: <Fault 1: 'getFileVariable() takes exactly 5 arguments (4 given)'>
    user@user-VirtualBox:~/twister/bin$

**Comment by bogdanpopescu** [comment]
The queue part is a bug. Please check the version of cli.py file and make sure it's 2.003

**Comment by sandhyamisra** [comment]
The queue option is now working. However, it is not clear where exactly the script/test case is getting queued. 
How do we run the test suite which has the newly queued test case?

For example when I queue a new script as below:

user@user-VirtualBox:/opt/twister/bin$ python cli.py --queue testg01:/home/user/twister/demo/testsuite-python/test_py_globals3.py 

Hello, user `user`.

Test `/home/user/twister/demo/testsuite-python/test_py_globals3.py` was queued in suite `testg01`.

Now, how does one run the testg01 suite? 

If testg01 is part of the project file MYGLOBALS.xml then does it modify the MYGLOBALS.xml to include the newly queued file ? (test_py_globals3.py) 

Atleast this is not what is happening currently. Please clarify.

# Check the log snippet below:

user@user-VirtualBox:/opt/twister/bin$ python cli.py -s start -p /home/user/twister/config/users/MYGLOBALS.xml -c /home/user

Hello, user `user`.

Must specify a valid config path, that path does not exist ! Exiting !

user@user-VirtualBox:/opt/twister/bin$ python cli.py -s start -p /home/user/twister/config/users/MYGLOBALS.xml -c /home/user/twister/config/fwmconfig.xml

Hello, user `user`.

Starting...
running

user@user-VirtualBox:/opt/twister/bin$ python cli.py --details
Hello, user `user`.

User status : stopped
Last started: 2013-07-10 14:41:33
Time elapsed: 0:00:04

Your Suites are:
- on EP-1001 :
  - testg01
    - [pass] /home/user/twister/demo/testsuite-python/test_py_globals1.py
    - [pass] /home/user/twister/demo/testsuite-python/test_py_globals2.py
- on EP-1002 :
  - nothing here
- on EP-1003 :
  - nothing here
- on EP-1004 :
  - nothing here
- on EP-1005 :
  - nothing here

user@user-VirtualBox:/opt/twister/bin$

**Comment by croqaz** [comment]
Hello,
You can queue files only during runtime, the queue is not persistent.
For example, while you run suite1, you want to add a few tests at the end, but don't want to interrupt the run of the current tests. This is when you can use queue, to append you tests.
If you queue the tests before a run, when you START, the central engine will read the XML and completely overwrite your queued files.
Also, don't forget that you cannot see the queued files in the applet.
I hope this answers your question.

**Comment by sandhyamisra** [comment]
During runtime queuing works as expected.

**Comment by bogdanpopescu** [comment]
Closing issue

**Comment by rajanberi** [comment]
how  to create new sut using cli?

**Comment by croqaz** [comment]
Hello Rajanberi,

The short answer is: you can't, using the provided "cli.py" script, from
the "bin" folder.

However, you can write a Python script that can automate the creating of
a new SUT.

```
#!/usr/bin/python

from xmlrpclib import ServerProxy

user = 'YOUR USERNAME
pwd = 'YOUR PASSWORD'

s = ServerProxy('http://{}:{}@127.0.0.1:8000/'.format(user, pwd))

s.index_suts()

s.create_new_sut('NAME.user', '/', {})

```

The SUT name must end with ".user", or ".system", so that Twister knows
where to save the sut: globally, or just for your user.
The SUT will be created in the root.

Have a good day !

On Jo, 2015-02-19 at 02:27 -0800, rajanberi wrote:

> how to create new sut using cli?
> 
> —
> Reply to this email directly or view it on GitHub.

This e-mail and any attachment(s) are intended only for the recipient(s) named above and 
others who have been specifically authorized to receive them. They may contain confidential 
information. If you are not the intended recipient, please do not read this email or its 
attachment(s). Furthermore, you are hereby notified that any dissemination, distribution or 
copying of this e-mail and any attachment(s) is strictly prohibited. If you have received this 
e-mail in error, please immediately notify the sender by replying to this e-mail and then 
delete this e-mail and any attachment(s) or copies thereof from your system. Thank you.

**Comment by rajanberi** [comment]
hi
 i am getting output while running start_client.py script.
can you help me how to fix this issue?
Thanks

2015-Feb-24 16-51-48    ### Will REGISTER EPs on CE `127.0.0.1:8000` ::
`['rajan_auto']` ###
2015-Feb-24 16-51-48    Client Debug: Connected to CE at `127.0.0.1:8010`...
2015-Feb-24 16-51-48    _ERROR_ Cannot authenticate on CE path
`127.0.0.1:8010`!
Exception ReferenceError: 'weakly-referenced object no longer exists' in
<bound method Connection.__del__ of <rpyc.core.protocol.Connection 'conn1'
object at 0x7f21ced5d510>> ignored
2015-Feb-24 16-51-48    _ERROR_ Cannot connect to Central Engine at
`127.0.0.1:8000`! Will Retry forever and ever...

**Comment by rajanberi** [comment]
sir,

hii
what are the steps to create suite using CLI in twsiter as i didn't find
details about it in user guide .

**Comment by croqaz** [comment]
Hello,

Check the CLI option `run-test`. Can add a file in a suite, run blocking and then show the log. Specify the file name and the SUT.
You can only run 1 test like this.

**Comment by rajanberi** [comment]
Hi Cristi

How can i send start signal to EP using CLI?
thanks

**Comment by bogdanpopescu** [comment]
@rajanberi 
This is the syntax to start testing from cli:
python2.7 cli.py --login=<username>:<password> -c <path_to_fwmconfig.xml> -p <path_to_a_project_file> -s start

path_to_fwmconfig.xml - this is the absolute path to fwnconfig file. Usually the path is ~twister/config/fwmconfig.xml 
path_to_project_file - this is the name of a project file generated and saved from GUI

**Comment by rajanberi** [comment]
thanks

**Comment by rajanberi** [comment]
hi
i am able to run twister UI but there is some problem.I am not able to
create new project .I am attaching screenshot .Kindly have a look and if
possible help me.

Thanks
regards
Rajan

**Comment by bogdanpopescu** [comment]
@rajanberi 
Hi, I do not see any screenshot attached. Please re-post it.

**Comment by rajanberi** [comment]
refer to previous mail . screenshot attached

**Comment by rajanberi** [comment]
can u help me ? any clue
regarding previous mail.
 thanks

**Comment by bogdanpopescu** [comment]
@rajanberi 
Please make sure your user is added in file /opt/twister/config/users_and_groups.ini file, like in the following example:

[[user]]
                groups_production = admin, user
                groups_development = admin, user
                timeout = 01
                key = 2852ba07f5aceef61d8429c14497216e

**Comment by rajanberi** [comment]
Thanks a lot

**Comment by rajanberi** [comment]
hi Bogdan,

can u tell me what to define in " Run on Sut" and how to do it? because i
am not able to to so .

i am attaching screenshot.

Thanks

**Comment by rajanberi** [comment]
hi sir,
do you have any idea regarding my previous email.

regards
rajan
