### ISSUE TITLE
While running scripts in gui, the first test case file is not displayed in GUI (it is displayed in the edit window however)

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#28]
While running a test suite which contains 3 test scripts for example in GUI, only execution status of the second and third are getting displayed in GUI, the first one is not displayed. However, in EP-1001_CLI.log the status of all 3 scripts are shown.

Twister version: 8th July

Before running the testsuite:
![beforerunning](https://f.cloud.github.com/assets/4291567/768245/f1365114-e89b-11e2-9434-2b18253a5c07.JPG)

After running:
![afterrunning](https://f.cloud.github.com/assets/4291567/768249/f76a351e-e89b-11e2-8beb-ade2e15e605b.JPG)

**Comment by bogdanpopescu** [comment]
@sandhyamisra  This issue was spotted and fixed in version 2.011 of the GUI delivered on 9th July

**Comment by sandhyamisra** [comment]
This works fine with Version 2.011 of the GUI. Can be closed

**Comment by bogdanpopescu** [comment]
Closing issue
