### ISSUE TITLE
Clear log button should reconfirm from the user whether the logs should be erased

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#29]
Clear log button should reconfirm from the user whether the logs should be erased

When we click on the clear log button in the log window, the logs are immediately deleted/cleared. We suggest that a pop up message should be displayed to get the user confirmation for clearing/erasing the logs.

![clear log](https://f.cloud.github.com/assets/4291567/768271/71b7ec3a-e89c-11e2-8326-9f90bc5ee553.JPG)

**Comment by bogdanpopescu** [comment]
@sandhyamisra  This is ready to verify. Please confirm if the issue is fixed or not.

**Comment by sandhyamisra** [comment]
Works fine can be closed
