### ISSUE TITLE
Issue in Editing property names/deleting the property of a component under TestBed

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#3]
Here are the steps to reproduce the above problem:
1.  Under the configuration tab in Twister, add a component (C1) for any tbx.
2.  Add a property P1 to the component C1
3.  Edit the property name created above to let’s say Prop1 -> This is not allowed. Only the first character is taken.
4.  Try to delete the property created in step 2 -> Unable to delete the property. No error message is seen.

An alternative way to see the problem:
1.  Edit the property name of any existing component.
2.  Leave the property window, then return.  Note that the property name reverted back to the original.
3.  For the selected property, hit the remove button.  Note that the property is not removed.  No error message is seen.
4.  Removing the component will remove all the properties.  Not a good way to fix the problem.

So there are a couple of issues here:
1.  The property name cannot be edited
2.  Any property whose name was edited cannot be removed

**Comment by bogdanpopescu** [comment]
Fixed with the submission on 17th May ( Rlease_2.002 tag )
@sandhyamisra  Please verify it

**Comment by sandhyamisra** [comment]
This is working as expected. Can be closed

**Comment by bogdanpopescu** [comment]
Closing issue.
