### ISSUE TITLE
Enhancement: Provide a way in Test Beds to copy/paste a testbed or component

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#31]
Some test bed descriptions can be large and contain many repetitive components.
A means (right mouse click?) to select an existing test bed or component and copy it. It should copy the component and all sub-components. Also, it should allow renaming and updating the id number.

**Comment by baluthomas** [comment]
Adding provision for Saving a testbed config and uploading a testbed config will be helpful.

**Comment by croqaz** [comment]
Export and import TB / SUT as XML is now implemented and will most likely land in the next release.
The XML format is identic with the format for global params and config files:
`root > folder (fname and fdesc) > param (name, value, desc, type)`

**Comment by CJHoffmann** [comment]
A right-mouse click on a testsuite provides a means to export a testsuite.  This is functional and dragging saved testsuite into a project also works.
