### ISSUE TITLE
Cannot save project if EP is not assigned to test bed

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#33]
If a test bed assigned to a test suite does not have an EP associated with it, the saving the project file fails without any indication why.  When an EP is then associated with the test bed, the project is saved.

It is expected that the project file will be saved whether or not an EP is assigned to the test bed.  An error should be displayed reporting that the project needs an EP assigned to the test bed.

**Comment by bogdanpopescu** [comment]
@CJHoffmann we cannot reproduce this; please indicate the GUI applet version

**Comment by CJHoffmann** [comment]
Create a new TB, but do not assign an EP to it.
![eperr01](https://f.cloud.github.com/assets/3911048/975280/51c14b20-0673-11e3-94cd-5decf2b0a893.jpg)

Create a project with the new TB assigned to it.
![eperr04](https://f.cloud.github.com/assets/3911048/975305/d016b0d2-0673-11e3-949f-2959c06f6323.jpg)

Save the project and note the popup message.  No indication why the save failed.
![eperr05](https://f.cloud.github.com/assets/3911048/975326/34d36d6c-0674-11e3-8466-c09c0eaf737e.jpg)

Assign an EP to the TB.
![eperr06](https://f.cloud.github.com/assets/3911048/975329/5536728e-0674-11e3-9188-bb8713d244e2.jpg)

Saving the project is now successful.
![eperr07](https://f.cloud.github.com/assets/3911048/975331/68b36a38-0674-11e3-8c72-724f0ca9f53e.jpg)

GUI Version:
![eperr08](https://f.cloud.github.com/assets/3911048/975332/70894ad4-0674-11e3-9ad7-441fb1bb2a5c.jpg)

**Comment by CJHoffmann** [comment]
When a project is saved, a warning is now declared if any test suite is assigned to a SUT that does not have an EP assigned to it.  The project file is saved.
Works as expected.
