### ISSUE TITLE
The log panel slider is not working cleanly. I cannot easily read the messages. The messages should probably wrap at 80 chars. 

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#35]

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Could you please provide a snapshot to understand the issue ?
Thanks.

**Comment by mtkuntz** [comment]
![logs_snap](https://f.cloud.github.com/assets/4291929/872812/657d68fe-f86a-11e2-9269-7c9344c5dbea.jpg)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify if the issue is fixed.

**Comment by mtkuntz** [comment]
The slider issue is not fixed, I am using V:.2.017

**Comment by mtkuntz** [comment]
I created Issues #73, please close this one.
