### ISSUE TITLE
Twister doesn't execute the pre-execution and post-execution scripts

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#4]
Problem Description: Twister doesn't execute the pre and post execution scripts

Steps to reproduce the issue:
1. Create a project named example
2. Create a Test suite and add to the project and select one script in the testsuite
3. Provide a pre-execution script and post execution script from the Twister GUI. (Check the attached screenshot)

Result: Twister doesn't execute the pre and post execution scripts. It just executes the Test Suite scripts. 

![pre postexecution](https://f.cloud.github.com/assets/4291567/476979/1c5ab6be-b7d2-11e2-9807-9bd077ecec46.jpeg)

Example.xml

<Root>
    <stoponfail>false</stoponfail>
    <ScriptPre>/home/user/twister/demo/testsuite-python/init.py</ScriptPre>
    <libraries/>
    <ScriptPost>/home/user/twister/demo/testsuite-python/test_py_printnlogs.py</ScriptPost>
    <dbautosave>false</dbautosave>
    <tcdelay/>
    <TestSuite>
        <tsName>PROJECT</tsName>
        <PanicDetect>false</PanicDetect>
        <TbName>tb1</TbName>
        <UserDefined>
            <propName>Run_Number</propName>
            <propValue>1</propValue>
        </UserDefined>
        <TestCase>
            <tcName>/home/user/twister/demo/testsuite-python/test_py_globals1.py</tcName>
            <Property>
                <propName>Runnable</propName>
                <propValue>true</propValue>
            </Property>
            <Property>
                <propName>Running</propName>
                <propValue>true</propValue>
            </Property>
        </TestCase>
        <TestCase>
            <tcName>/home/user/twister/demo/testsuite-python/test_py_globals2.py</tcName>
            <Property>
                <propName>Runnable</propName>
                <propValue>true</propValue>
            </Property>
            <Property>
                <propName>Running</propName>
                <propValue>true</propValue>
            </Property>
        </TestCase>
    </TestSuite>
</Root>
## Log File:

Py debug: For EP EP-1001, CE Server returned a new status: running.
EP debug: Received start signal from CE!
TC debug: TestCaseRunner started with  User: user ;  EP: EP-1001.
TC debug: Connected to proxy, running tests!
Downloading library `TestBed.py` ...
Downloading library `Threads.py` ...
Downloading library `TscFtp.py` ...
Downloading library `TscTelnet.py` ...

===== ===== ===== ===== =====
  Starting suite `100:PROJECT`
===== ===== ===== ===== =====

<<< START filename: `1000:/home/user/twister/demo/testsuite-python/test_py_globals1.py` >>>

Debug: dependancy = ` `, prereq =`False`, optional =`False` ...

Root level params: ['NE1']
All params for Level_1: False
All params for Level_1/Level_2: False 

First level global #1: False 

Will set new value to:: value_16_69e14d421bd2e87674d89779ecba3535
Check value changed:: False
Will set new value to:: value_18_d8073edfc7cd4e1fada7cc52699d7bde72db
Check value changed:: False
Will set new value to:: value_11_0e3d59d0d0a18e00b579eb
Check value changed:: False
Will set new value to:: value_13_97b1b270879bb66f6aa126e275
Check value changed:: False
Will set new value to:: value_2_65fa
Check value changed:: False
Will set new value to:: value_10_92235c3a0312e622a378
Check value changed:: False
Will set new value to:: value_11_23d999485787341e141787
Check value changed:: False
Will set new value to:: value_2_168e
Check value changed:: False
Will set new value to:: value_7_279a047fc22530
Check value changed:: False
Will set new value to:: value_9_a7b823edc19ee0b89d
Check value changed:: False

> > > File `/home/user/twister/demo/testsuite-python/test_py_globals1.py` returned `PASS`. <<<

<<< END filename: `1000:/home/user/twister/demo/testsuite-python/test_py_globals1.py` >>>

<<< START filename: `1001:/home/user/twister/demo/testsuite-python/test_py_globals2.py` >>>

Debug: dependancy = ` `, prereq =`False`, optional =`False` ...

Setting 2 functions, 2 classes and 2 instances, for using in the next tests!

> > > File `/home/user/twister/demo/testsuite-python/test_py_globals2.py` returned `PASS`. <<<

<<< END filename: `1001:/home/user/twister/demo/testsuite-python/test_py_globals2.py` >>>

===== ===== ===== =====
. . . All tests done . . .
===== ===== ===== =====

EP debug: Successful run!

Py debug: For EP EP-1001, CE Server returned a new status: stopped.

**Comment by bogdanpopescu** [comment]
Please make sure that your pre and post execution scripts can be executed in shell ( try them in a terminal ). Check that they are set as executable files.

To make them executable:
$ chmod +x init.py

The first line in your scripts should be like:
#!/usr/local/bin/python

**Comment by CJHoffmann** [comment]
I have researched the current documentation and could not find any specifics regarding the requirements of the pre and post execution scripts, especially how they differ from a test case script.

Please add the comments you provided earlier and any other details that might be needed for creating a pre and post execution script.

**Comment by croqaz** [comment]
Pre execution script = the script from this path will be executed by the Central Engine before running any test. The script can be written in any language (Perl, TCL, Java, can be a binary executable, etc). You cannot use a normal Twister test as a Pre/ Post exec script !  If you write a script in an interpreted language, don’t forget to add `#!/usr/bin/env ...your_language` on the first line.
If the file is not executable, CE will automatically run `chmod +x` on the file.
The documentation will be updated with this information.
