### ISSUE TITLE
Test Failure icon does not match User Doc

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#40]
The test failure icon displayed in project panel after a test failure does not match icon shown in section 8 of the user guide.

![testfailicon](https://f.cloud.github.com/assets/3911048/800286/4501686c-ed86-11e2-9ab7-80e3c434aad0.jpg)

**Comment by bogdanpopescu** [comment]
Documentation issue, we'll fix the user guide.

**Comment by bogdanpopescu** [comment]
@CJHoffmann User guide updated to show the correct fail icon.Please verify.

**Comment by CJHoffmann** [comment]
The icon shown in the documentation matches what is seen in Twister.  Can be closed.
