### ISSUE TITLE
Status of test case following failed setup is displayed as stopped in project panel and aborted in CLI

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#41]
After executing a project where a setup script fails, the following test cases are reported stopped in the project panel and aborted in the CLI log panel.  The User Doc suggests that the status should be reported as aborted.  This is preferred, rather than stopped.

![teststatusabort](https://f.cloud.github.com/assets/3911048/800317/e44ccc7c-ed86-11e2-9153-f72917120c37.jpg)

**Comment by CJHoffmann** [comment]
Since the test case is not executed if a setup script fails, perhaps the test case status should be reported as skipped, or not executed.

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Fix provided in 09th August delivery

**Comment by CJHoffmann** [comment]
I see no changes in the behavior.

![teststatusabort_2](https://f.cloud.github.com/assets/3911048/975600/1a31af44-067b-11e3-9e14-11422bad2b6c.jpg)

**Comment by bogdanpopescu** [comment]
Tested on GUI version 2.020

![issue_41](https://f.cloud.github.com/assets/1727668/984397/bf9d4274-089a-11e3-978f-b3803f6297e4.JPG)

**Comment by CJHoffmann** [comment]
I get the same results with GUI V2.021
