### ISSUE TITLE
Testcase Filename contains '//' in CLI log

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#42]
In the CLI, whenever the full pathname of a file is displayed, it contains two backslash characters.  Testcases were part of a testsuite copied from the Predefined Suites tab.

![testfilenamepath](https://f.cloud.github.com/assets/3911048/800358/9523d9fa-ed87-11e2-9efc-81ec48ab261c.jpg)

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Please verify is the issue is fixed.

**Comment by CJHoffmann** [comment]
Testsuites and projects that were previously saved still displayed '//'.  New testsuites and projects are saved and displayed correctly.
