### ISSUE TITLE
my email password is save in clear text in email.xml. provide method for using crypt ( ); or other solution to obscure it.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#43]
<Root>
    <Enabled>true</Enabled>
    <SMTPPath>smtp.mail.yahoo.com</SMTPPath>
    <SMTPUser>tester</SMTPUser>
    <SMTPPwd>1234</SMTPPwd> <--- this is the password entered via the GUI
    <From>tester@yahoo.com</From>
    <To>manager@yahoo.com</To>
    <Subject>This should appear in the Subject Line</Subject>
    <Message>This is my alternate message.</Message>
</Root>

**Comment by mtkuntz** [comment]
same issue in db.xml

**Comment by bogdanpopescu** [comment]
@mtkuntz  Re-opening, it was closed accidentally.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix provided in 09th August delivery

**Comment by mtkuntz** [comment]
OK to close.
