### ISSUE TITLE
Last testcase becomes inaccessible after another testcase is set to setup or teardown

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#44]
1) A project is created with many testcases and testsuits that fills a project panel
![projectpanel01](https://f.cloud.github.com/assets/3911048/807172/7dd7d220-ee49-11e2-8b6d-33f7bcc4e650.jpg)

2) After one or more testcases are set to setup or teardown the bottom testcase becomes inaccessible.  The slider does not allow displaying the last testcase.
![projectpanel02](https://f.cloud.github.com/assets/3911048/807175/87f4c240-ee49-11e2-836a-0af921e667c2.jpg)

3) If a non-setup or non-teardown testcase or testsuite is selected, the slider is then able to display the last testcase.

**Comment by bogdanpopescu** [comment]
@CJHoffmann we cannot reproduce this. Please indicate the "look & feel" style set and the OS of the host where the browser is started.

**Comment by bogdanpopescu** [comment]
@CJHoffmann  we managed to reproduce the issue. We'll provide a fix.

**Comment by bogdanpopescu** [comment]
@CJHoffmann  fix provided for this issue
