### ISSUE TITLE
After setup testcase fails remaining setup testcases are still executed

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#45]
A testsuite is created that contains mulitple setup testcases.
If one setup testcase fails, the remaining testcases are executed.
As expected, the regular testcases are skipped and the teardown testcases are executed.
![mulitplesetup01](https://f.cloud.github.com/assets/3911048/807262/23daa3d6-ee4b-11e2-9082-e46105792290.jpg)

It is expected that any remaining setup and regular testcases should be skipped following a setup testcase failure.

**Comment by croqaz** [comment]
`If one setup testcase fails, the remaining testcases are executed.`
You mean - "the remaining setup files are executed" ? In this case yes, that's true.
So, from what i understand, all remaining setup and normal files should skip, only the TEARDOWN files should be executed ?
Please confirm and i will start working on that.

**Comment by bogdanpopescu** [comment]
@CrConstantin  it is written bellow the picture: "It is expected that any remaining setup and regular testcases should be skipped following a setup testcase failure".

**Comment by bogdanpopescu** [comment]
@CJHoffmann  Fix provided on 17th July; please verify it

**Comment by CJHoffmann** [comment]
Thanking very much.  This behaves as expected.  Can be closed.
