### ISSUE TITLE
Additional Setup status conditions should cause remaining testsuite to be skipped.

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#46]
A project contains a testsuite with setup and regular testcases.
Currently only when _RESULT = 'fail' or if a coding exception is generated within a setup script are the remaining testcases skipped.
User Docs (Section 8 - How to Run the Test Files) states that 'abort' and 'not executed' are also status conditions where the setup did not end as expected.  'timeout' and 'invalid' are other _RESULT conditions that may indicate that the setup did not end as expected.
![setupstatus](https://f.cloud.github.com/assets/3911048/807975/d22dae8a-ee58-11e2-98da-c4fcadbda7d9.jpg)

**Comment by bogdanpopescu** [comment]
@CrConstantin  please investigate

**Comment by croqaz** [comment]
Confirmed. Currently, only the FAIL or crash error from a setup file are considered to make all the suite SKIP.
I will work on this, so only the PASS status from a setup file makes the suite continue.

**Comment by bogdanpopescu** [comment]
@CJHoffmann fix provided on 17th July; please verify it

**Comment by CJHoffmann** [comment]
I would suggest that 'skipped' setup testcases be treated as if the Runnable parameter was not set.  That is, the remaining setup and normal testcases should still run.

**Comment by CJHoffmann** [comment]
Verified with GUI V2.018
When setup test cases do not execute sucessfully, the remaining test cases are not run.  Test cases that are marked as teardown are always executed.

This issue can be closed.
