### ISSUE TITLE
Spelling mistake in a warning message

### ISSUE THREAD

**Issue by baluthomas** [Luxoft/Twister#47]
"SMTPPath tag si empty in framework config"
![issue](https://f.cloud.github.com/assets/4620117/811432/8b73f0a4-eed4-11e2-9467-f945901397fc.jpg)

It should be SMTP Path tag is empty in framework config.

Warning message is displayed while loading the framework GUI

**Comment by bogdanpopescu** [comment]
@baluthomas  That is the intent to display the name of the tag that should be present in fwmconfig.xml file.

**Comment by baluthomas** [comment]
si to is?

**Comment by bogdanpopescu** [comment]
@baluthomas Oh, sorry, I didn't spotted that. We'll correct.

**Comment by baluthomas** [comment]
same for one more warning while loading. have a look in to it also.

**Comment by bogdanpopescu** [comment]
@baluthomas  would you please indicate what is the second warning message with the same issue ?

**Comment by bogdanpopescu** [comment]
@baluthomas  the latest GUI contain fixes for the message issues

**Comment by baluthomas** [comment]
Verified. Can close this issue.
