### ISSUE TITLE
EP_HOST cannot be commented out or null. 

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#48]
EP_HOST is an optional keyword in epname.ini.

If lines:
EP_HOST =
or
# EP_HOST = some ip address

are used to disable the feature,  the EP does not start. 
Only if the line is removed will the EP start.

**Comment by bogdanpopescu** [comment]
@CJHoffmann fix provided for this issue

**Comment by CJHoffmann** [comment]
Verified in V2.018
EP_HOST keyword can now be disabled with an empty field or # comment delimiter.
