### ISSUE TITLE
Jcampbel!* Logs path `None` is invalid! Using master config `None` and suites config `None`.” No test will run client started on same host with real ip addresses instead of loopback version 2.015

### ISSUE THREAD

**Issue by JimCamp** [Luxoft/Twister#51]
Issue is fixed in delivery of 07/30/2013

**Comment by JimCamp** [comment]
This is blocking any further deployments of Twister. Is there something minor wrong or does the system in 2.015 not work when specifying actual ip addresses for the EPs and CEs

**Comment by bogdanpopescu** [comment]
@JimCamp  So, if you have real IP addresses in epnames.ini for EP_HOST and CE_IP it is not working ? Is the start_client starting ? Does it have access to conect to the CE port ?
I don't understand what is with the "Logs path `None` is invalid! Using master config `None` and suites config `None`.” message. Can you send some details ?

**Comment by JimCamp** [comment]
Bogdan,
That is the error messages that are displayed. I do not know for sure that there is not some little mistake made. So I included them to try to be helpful.
Initially I configured the ce on machine 1 and the  ep to be on machine 2. I did not manually start the client and no client was started no tests would run.
So then in the same config I started the client on machine 2 manually. Still no EP was started when I started a test. I could see the client running.
Then I configured the ep to run on machine 1 and connect to the ce on machine 1, both via real ip address. I manually started the start_client and still no eps were started when  run a test.
In the last config I tried to debug and this is what  I saw
I manually started the start_client and I see keep alive messages but nothing more.
Thanks
Jim Campbell

**Comment by bogdanpopescu** [comment]
@JimCamp  I see, please confirm that you have the latest GUI, CE and EP reinstalled. We didn't have this issue during testing, but I will double check ASAP.

**Comment by JimCamp** [comment]
Version installed is 2.015 from last Thursday.  All components installed, client installed from scratch on second install.
Thanks
Jim Campbell

**Comment by bogdanpopescu** [comment]
@JimCamp  
Hi Jim, 

We tried to reproduce this behavior in different ways without success. Every time the configuration is good the system behaves correctly. We tried over NIS/NFS with the same result. Could you please send me the log of CE ( server_log.log ), the epname.ini and the client log ( $HOME/twister/twisterclient.log ) ? 
Basically, every time the client is started, you should see this kind of message in server_log.log:

reset: Project: RESET operation took 0.0000 seconds.
registerClient: Client register `nisuser` -> {"11.126.32.9:4444": ["EP-tsc_2", "EP-tsc_1"]}.

Thanks,
Bogdan.

**Comment by JimCamp** [comment]
Bogdan,
Is my epname.ini file configured correctly and  valid? I see one from another user that has ENABLED lines on each EP entry?
Hosts running program are Redhat Linux.
Thanks
Jim Campbell

# Each section must be the name of an Execution Process.

# The name of an Execution Processes MUST be UNIQUE !

# The CE_IP and CE_PORT will be used by each EP, to connect to Central Engine.

# EP_HOST is used to filter what EPs can be started on the machine; if

# there is a match between the EP_HOST and the local machine, the EP is started

# If EP_HOST tag is not present, the EP is allowed to start by edfault

# For sniffer configuration ENABLED = 1 means that the sniffer will start,

# when executing ./start_ep.py, from twister/bin folder and ETH_INTERFACE = eth0

# reffers to sniffer ethernet interface.

[PACKETSNIFFERPLUGIN]
ENABLED                 =       1
ETH_INTERFACE   =       eth0

[EP-1001]
CE_IP   =       168.127.132.68
CE_PORT =       8000
EP_HOST =       168.127.132.68

**Comment by JimCamp** [comment]
Bogdan,
From server log file no entries that are not on loopback.
registerClient: Client register `cwispell` -> {"127.0.0.1:4444": ["EP-1001"]}.
registerClient: Client register `choffman` -> {"127.0.0.1:4446": ["EP-1004", "EP-1005", "EP-1001", "EP-1002", "EP-1003"]
Thanks

## Jim Campbell

From: Campbell, James
Sent: Wednesday, July 24, 2013 12:56 PM
To: 'Luxoft/Twister'
Subject: RE: [Twister] Jcampbel!\* Logs path `None` is invalid! Using master config `None` and suites config `None`.” No test will run client started on same host with real ip addresses instead of loopback version 2.015 (#51)

Bogdan,
Is my epname.ini file configured correctly and  valid? I see one from another user that has ENABLED lines on each EP entry?
Hosts running program are Redhat Linux.
Thanks
Jim Campbell

# Each section must be the name of an Execution Process.

# The name of an Execution Processes MUST be UNIQUE !

# The CE_IP and CE_PORT will be used by each EP, to connect to Central Engine.

# EP_HOST is used to filter what EPs can be started on the machine; if

# there is a match between the EP_HOST and the local machine, the EP is started

# If EP_HOST tag is not present, the EP is allowed to start by edfault

# For sniffer configuration ENABLED = 1 means that the sniffer will start,

# when executing ./start_ep.py, from twister/bin folder and ETH_INTERFACE = eth0

# reffers to sniffer ethernet interface.

[PACKETSNIFFERPLUGIN]
ENABLED                 =       1
ETH_INTERFACE   =       eth0

[EP-1001]
CE_IP   =       168.127.132.68
CE_PORT =       8000
EP_HOST =       168.127.132.68

**Comment by bogdanpopescu** [comment]
@JimCamp 

Please provide me the epname.ini, twisterclient.log and server_log.log files.
Please make sure the CE_IP is the same as the one specified in epname.ini and EP_HOST is the same as specified in epname.ini. Please restart start_client if you update epname.ini.

Many thanks,
Bogdan.

**Comment by JimCamp** [comment]
Bogdan,

I cannot send the server log it is very large, If you would like some greps from the log that might be possible. Let me know what you need to see.
I think the problem is not in the server as you can see below from the client log.

-bash-4.1$ cat  twisterclient.log
Twister Client Service init..
Found `0` EPs: ``.

Could not establish server on any port! Exiting!
-bash-4.1$ cat epname.ini

# Each section must be the name of an Execution Process.

# The name of an Execution Processes MUST be UNIQUE !

# The CE_IP and CE_PORT will be used by each EP, to connect to Central Engine.

# EP_HOST is used to filter what EPs can be started on the machine; if

# there is a match between the EP_HOST and the local machine, the EP is started

# If EP_HOST tag is not present, the EP is allowed to start by edfault

# For sniffer configuration ENABLED = 1 means that the sniffer will start,

# when executing ./start_ep.py, from twister/bin folder and ETH_INTERFACE = eth0

# reffers to sniffer ethernet interface.

[PACKETSNIFFERPLUGIN]
ENABLED                 =       1
ETH_INTERFACE   =       eth0

[EP-1001]
CE_IP   =       168.127.132.68
CE_PORT =       8000
EP_HOST =       168.127.132.68

-bash-4.1$ ps -ef | grep start
jcampbel  3314  5698  0 14:51 pts/4    00:00:00 grep start
jcampbel  4099     1  0 Jul18 pts/3    00:07:14 /usr/bin/python -u /home/jcampbel/twister/bin/start_client.py
mkuntz    6966     1  0 Jul22 ?        00:01:20 /usr/bin/python -u /home/mkuntz/twister/bin/start_client.py
cwispell 15707     1  0 Jul18 ?        00:07:26 /usr/bin/python -u /home/cwispell/twister/bin/start_client.py
choffman 26267     1  0 Jul18 ?        00:07:15 /usr/bin/python -u /home/choffman/twister/bin/start_client.py

**Comment by bogdanpopescu** [comment]
@JimCamp 

Thanks Jim.
And what about the IP addresses for CE and EP ?

Thanks,
Bogdan

**Comment by JimCamp** [comment]
Bogdan,
What I was tried first was a real config where the EP runs on another box, preferably auto started.
That did not work so I moved to a basic and unsupportable config of all running on one box, but not using the loopback address.
The files I have provided are from that config.

Thanks
Jim Campbell

You can see them from the config file.
…
[EP-1001]
CE_IP   =       168.127.132.68
CE_PORT =       8000
EP_HOST =       168.127.132.68

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State
tcp        0      0 0.0.0.0:22                  0.0.0.0:\*                   LISTEN
tcp        0      0 127.0.0.1:631               0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:25                  0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:41817               0.0.0.0:\*                   LISTEN
tcp        0      0 127.0.0.1:6010              0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:4444                0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:4445                0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:4446                0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:4447                0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:8000                0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:3306                0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:587                 0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:52683               0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:111                 0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:80                  0.0.0.0:\*                   LISTEN
tcp        0      0 0.0.0.0:977                 0.0.0.0:\*                   LISTEN

network config

eth0      Link encap:Ethernet  HWaddr D8:D3:85:5D:5A:E6
          inet addr:168.127.132.68  Bcast:168.127.132.255  Mask:255.255.255.0
          inet6 addr: fe80::dad3:85ff:fe5d:5ae6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3685894 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2440233 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:683302775 (651.6 MiB)  TX bytes:454158053 (433.1 MiB)
          Memory:fb760000-fb780000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:10557375 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10557375 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2172614739 (2.0 GiB)  TX bytes:2172614739 (2.0 GiB)

-b
