### ISSUE TITLE
How to Connect Controller and Virtual Switch with Twister

### ISSUE THREAD

**Issue by devikiran** [Luxoft/Twister#55]
Thanks for providing Twister as an Opensource,i did the setup of Twister Framework and was able to Run the Demo Test cases with EP's Running Successfully.
i am eager to know whether there is  a way to connect Controller and a  Virtual Switch and are there some test cases exposed to conformance test for openflow protocol Testing?

**Comment by bogdanpopescu** [comment]
@devikiran 
Hi,

Sorry, this is not in the scope of Twister framework as posted on github so I cannot provide detailed information.
You will have to find a way to define the parameters for controller and virtual switch using test bed mechanism.

Best regards,
Bogdan.

**Comment by baluthomas** [comment]
Hi Devikiran,
Can u describe how you manually connect to controller and switch
