### ISSUE TITLE
cli.py version number not correctly reported

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#56]
Currently, cli.py --version reports v2.0, However, looking at the cli.py file it shows that the version is 2.006.  See below:

---

prompt$ /usr/local/bin/python2.7 cli.py --version
cli.py v2.0

prompt$ head cli.py
# !/usr/bin/env python
# version: 2.006

---

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Please verify is the issue is fixed.

**Comment by CJHoffmann** [comment]
It works as expected
