### ISSUE TITLE
SSH_twist demo crashes

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#57]
After a fresh install and editing the necessary config files, the python demo script test_py_ssh_twist.py crashes because unable to import TscSshLib

<<< START filename: `1009:/home/user/twister/demo/testsuite-python/test_py_ssh_twist.py` >>>

Exception:
Traceback (most recent call last):
  File "/home/user/twister//client/executionprocess/TestCaseRunner.py", line 532, in run
    result = current_runner._eval(str_to_execute, globs, args)
  File "/home/user/twister/client/executionprocess/TestCaseRunnerClasses.py", line 261, in _eval
    execfile(fpath, globs_copy)
  File "/home/user/twister//.twister_cache/EP-1001/test_py_ssh_twist.py", line 8, in <module>
    from TscSshLib import SshManager
ImportError: No module named TscSshLib

> > > File `/home/user/twister/demo/testsuite-python/test_py_ssh_twist.py` execution CRASHED. <<<

Test statistics: Start time 2013-07-31 15:11:58 -- End time 2013-07-31 15:12:00 -- 1.77 sec.

<<< END filename: `1009:/home/user/twister/demo/testsuite-python/test_py_ssh_twist.py` >>>

**Comment by baluthomas** [comment]
instead of 'from TscSshLib import SshManager', use from ce_libs.TscSshLib import SshManager

and in line no 93 logMsg function should be called as logMsg(logRunning, "msg")

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Fix provided in 09th August delivery

**Comment by CJHoffmann** [comment]
Tested with 16th August delivery.

The test_py_ssh_twist.py SSH demo still fails. 

From the CLI log file.
[choffman@pearl327 logs]$ more EP-1002_CLI.log
User: choffman ;  EP: EP-1002 ;  host: 127.0.0.1:8000
EP debug: Setup done, waiting for START signal.
Debug: CE returned status `running` for `EP-1002`.
EP debug: Received start signal from CE!
TC debug: TestCaseRunner started with  User: choffman ;  EP: EP-1002.
Downloading library `TscCommonLib.py` ...
Downloading library `TscTelnetLib.py` ...
TC debug: Connected Central Engine, running tests!

===== ===== ===== ===== =====
 Starting suite `101 - Test01`
===== ===== ===== ===== =====

Downloading library `TscCommonLib.py` ...
Downloading library `TscSshLib.py` ...

<<< START filename: `1001:/home/choffman/twister/demo/testsuite-python/test_py_ssh_twist.py` >>>

Exception:
Traceback (most recent call last):
  File "/home/choffman/twister//client/executionprocess/TestCaseRunner.py", line 547, in run
    result = current_runner._eval(str_to_execute, globs, args)
  File "/home/choffman/twister/client/executionprocess/TestCaseRunnerClasses.py", line 261, in _eval
    execfile(fpath, globs_copy)
  File "/home/choffman/twister//.twister_cache/EP-1002/test_py_ssh_twist.py", line 8, in <module>
    from ce_libs import SshManager
ImportError: cannot import name SshManager

> > > File `/home/choffman/twister/demo/testsuite-python/test_py_ssh_twist.py` execution CRASHED. <<<

Test statistics: Start time 2013-08-16 13:58:39 -- End time 2013-08-16 13:58:39 -- 0.09 sec.

<<< END filename: `1001:/home/choffman/twister/demo/testsuite-python/test_py_ssh_twist.py` >>>

![failssh](https://f.cloud.github.com/assets/3911048/977195/a15f71e0-069e-11e3-94bd-83948a9c1b1d.jpg)

**Comment by CJHoffmann** [comment]
SSH_twist demo now works as expected.
