### ISSUE TITLE
Database updates fail

### ISSUE THREAD

**Issue by toma010** [Luxoft/Twister#59]
from server_log.log

commitToDatabase: CE: Preparing to save into database...
saveToDatabase: MySQL Error 1045: Access denied for user 'user'@'localhost' (using password: YES)!
commitToDatabase: CE: Could not save to database!

**Comment by baluthomas** [comment]
It seems like the database is not allowing the user to login. Either the password you provided is wrong or 'user' is not having the right to access the database.
Try to login manually to the database.
The error message is thrown by MySQL

http://hintsforums.macworld.com/showthread.php?t=58057

**Comment by bogdanpopescu** [comment]
@toma010 
Please make sure the user is created and it has privileges for that database.
Here are some tips on how to create user and grant privileges:

Using a privileged database user ( e.g. mysql root ), login to mysql ( mysql -u root ) and do the commands:
create user 'user'@'localhost' identified by 'password';
grant all on . to 'user'@'localhost';
flush privileges;

That should enable user to write into database.

**Comment by baluthomas** [comment]
is this a bug?

**Comment by bogdanpopescu** [comment]
Yes, it is a bug introduced user users&groups feature. Fix is in progress.

**Comment by bogdanpopescu** [comment]
@toma010 
Fix provided in 09th August delivery

**Comment by toma010** [comment]
Fix verifed
