### ISSUE TITLE
Takes 5 minutes for Reports tab to return control to user.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#60]
I click on the Reports tab and the browser consistently takes 5 minutes to  present the Report Menu page.

**Comment by baluthomas** [comment]
just type localhost:8000 in the browser and see if it is taking time t load. This should be some issue with network i believe.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
OK to close
