### ISSUE TITLE
Dependencies between test case <Feature Request>

### ISSUE THREAD

**Issue by baluthomas** [Luxoft/Twister#61]
A new feature should be added to the framework by which users will be able to create test dependencies.

E.g.
i) If in a test suite there are 10 test cases, the user will not want the test case no: 5 to run if test case no: 2 fails. That means test 5 is depended of test 2.

ii) The test case no: 7 should only run if and only if test case 4 fails.

Currently there is direct way to implement this. When user right clicks a particular testcase, there should be an option to create dependencies. He will choose the dependent test cases from the suite.

**Comment by croqaz** [comment]
Hello,
This is a work in progress. Should be available in january 2014.
~ Cristi

**Comment by bogdanpopescu** [comment]
@baluthomas 
Hi,

We delivered the feature for test case dependencies. Please verify it.

**Comment by leanderc** [comment]
@CrConstantin @bogdanpopescu 
Hi,
I tried adding dependency within test cases.
Added 2 test cases to a test suite , adding dependency such that the second test case only runs is the first one fails.
returned _RESULT = "pass" in the first test case.
How ever the second test case is still executed. irrespective of the dependency flag set.
I am on build number

V.: 3.021 
Build date: 10.06.2014
x86_64 Linux, Ubuntu 12.04 precise
Python 2.7.3.final.0

**Comment by bogdanpopescu** [comment]
@leanderc 
Hi,
The issue is fixed and a new version was uploaded. Please install the server and the GUI and verify it.

**Comment by leanderc** [comment]
@bogdanpopescu 

I was in the process of verifying this bug on build number

V.: 3.025 
Build date: 12.08.2014
x86_64 Linux, Ubuntu 14.04 trusty
Python 2.7.6.final.0

However when i execute a test case i get the below error.

TWISTER_PATH is set to `/home/testuser/twister`.

EP Info: Connecting to the Central Engine...
EP Debug: Connected and authenticated to CE at `127.0.0.1:8000`.

EP Debug: Creating a threaded logger...
EP Debug: Created the logger.

~ Start the Execution Process ~
~ User: testuser ; EP: ubuntu_EP-testuser ; CE path: 127.0.0.1:8000 ~

Downloading library `TscCommonLib.py` ...
... all libraries downloaded.

EP Info: Start running the tests!

===== ===== ===== ===== =====
 Starting suite `102 - depedencycheck`
===== ===== ===== ===== =====

<<< START filename: `1002:/home/testuser/Pre-Deployment Verfication tests/Suite/Testcases//test.py` >>>

> > > File `/home/testuser/Pre-Deployment Verfication tests/Suite/Testcases//test.py` returned `pass`. <<<

Test statistics: Start time 2014-08-14 15:01:27 -- End time 2014-08-14 15:01:27 -- 0.14 sec.

EXCEPTION on changing file status `File "/home/testuser/twister/client/executionprocess/ExecutionProcess.py", line 1137, in tests
    proxy().set_file_status(self.epName, file_id, STATUS_PASS, timer_f) # File status PASS
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in **call**
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: 'bool' object has no attribute 'get'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict%28kwargs%29)
  File "/opt/twister/server/CeRpyc.py", line 937, in exposed_set_file_status
    return self.project.set_file_status(user, epname, file_id, new_status, time_elapsed)
  File "/opt/twister/server/CeProject.py", line 2335, in set_file_status
    suite_name = self.get_suite_info(user, epname, suite).get('name')
AttributeError: 'bool' object has no attribute 'get'`!
<<< END filename:`1002:/home/testuser/Pre-Deployment Verfication tests/Suite/Testcases//test.py` >>>

# 

# . . . All tests done . . .

**Comment by bogdanpopescu** [comment]
@leanderc 
Code has been updated, please verify.
