### ISSUE TITLE
User management hides the existing users frame when the screen resolution is 1366 x 768 or lower

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#65]
User management hides the existing users frame when the screen resolution is 1366 x 768 or lower that is the highest resolution available on a 14 inch screen laptop. Only when connected to an external monitor and a higher resolution is selected, the existing users panel shows up.

![usermanagementgui](https://f.cloud.github.com/assets/4291567/976097/941eb9d2-0685-11e3-9818-d82dacca040c.JPG)

**Comment by mtkuntz** [comment]
Separately, please make the max size wider to accommodate the Group Roles so we don't always need the scroller.
![group_roles](https://f.cloud.github.com/assets/4291929/977477/a156ac3a-06a4-11e3-8e22-0ca3f68a9674.jpg)

**Comment by bogdanpopescu** [comment]
@sandhyamisra  @mtkuntz 
Please verify fix provided on 23rd August load

**Comment by sandhyamisra** [comment]
Works fine with 23rd August load. Can be closed.
