### ISSUE TITLE
start_client start is not working if [PACKETSNIFFERPLUGIN] ENABLED = 1 

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#66]
start_client start is not working if [PACKETSNIFFERPLUGIN] ENABLED = 1 

set it to 0 and client was started

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Do you get any error ?
Can you send the $HOME/twister/client_log.log file to understand what is the issue ?

**Comment by mtkuntz** [comment]
We have not been able to reproduce this. Will retest after the next build.

**Comment by mtkuntz** [comment]
Now on V2.022, Have not seen this again, OK to Close
