### ISSUE TITLE
error in saving email to .xml

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#67]
gui sequence in V2:.021
1. I save my username and password.
2. Test email sent OK
3. I delete my password
4. I save again.
5. Twister, warns Password Not Set, the posts "File successfully saved."
6. Test email sent OK. // If twister had saved a null password the email server should have failed to authenticate.
7. twister should actually write the null password (encrypted) to the email.xml, such that authentication fails in 6.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify fix provided on 23rd August load

**Comment by mtkuntz** [comment]
OK to close - saving Null pid worked.
