### ISSUE TITLE
Summary does not show pending count; error_codes mapping not correct.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#68]
Count not shown for test that's pending.
Using V.2021
(running and pass seem to work)
![pending](https://f.cloud.github.com/assets/4291929/986788/ca165ca0-08df-11e3-9307-9bde678eccd9.jpg)

I set error codes and the summary was counting in the wrong bucket.
    error_code = "STOPPED", Summary Fail =1, should be "stopped"
    error_code = "INVALID", Summary Timeout =1, should be "stopped"

```
is error_code = "ABORTED" supported, it maps to "stopped"
```

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify fix provided on 23rd August load

**Comment by mtkuntz** [comment]
Pending status is fixed.

The other issue remains
I set error codes and the summary was counting in the wrong bucket.
error_code = "STOPPED", Summary shows Fail =1, should be "stopped"
error_code = "INVALID", Summary shows Timeout =1, should be "stopped" or "fail"

![mapping](https://f.cloud.github.com/assets/4291929/1027147/b6ea30ac-0e6b-11e3-8a72-fab200852415.jpg)

**Comment by mtkuntz** [comment]
INVALID is still not mapped correctly (using V.2:022) - it maps to timeout.
![invalid](https://f.cloud.github.com/assets/4291929/1089617/46769f16-1647-11e3-8d22-0f6628f47df1.jpg)
 from user guide
![icons](https://f.cloud.github.com/assets/4291929/1089618/4b456c84-1647-11e3-9cde-38dde5374ddb.jpg)

**Comment by mtkuntz** [comment]
I think "invalid" is not a valid return code. Perhaps just the sample test case test_py_printlogs.py has an incorrect comment.

#

# Must have one of the statuses:

# 'pass', 'fail', 'skipped', 'aborted', 'not executed', 'timeout', 'invalid'

_RESULT = test()

by the the user manual is inaccurate.
"success" should be "pass"
"failure" should be "fail"
"skip" should be "skipped"
"abort" should be "aborted"
missing "timeout"

**Comment by croqaz** [comment]
Hello,
The user manual updated on Friday (6-sept) will contain the detailed explanation on page 33.
You can return any status from your test: `pass`, `fail`, `skip` OR `skipped`, `abort` OR `aborted`, `timeout`, `not exec` OR `not executed` and `invalid`.
You cannot use the status `working` or `pending` as a finish status.
I hope this solves the confusion.

**Comment by mtkuntz** [comment]
Please remove "invalid" from ALL sample programs, ex:  test_py_printlogs.py
thanks

**Comment by mtkuntz** [comment]
Invalid is still not fixed - writing a new Issue,
