### ISSUE TITLE
Clear log not working. 

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#69]
tried clearing EP-1002_CLI.log from the GUI. The log is not cleared. Using V2:.021

Here's the error from the server_log.

resetLog: Log Error! Log type `EP-1002_CLI.log` is not in the list of defined types: `{'logSummary': '/home/mkuntz/twister/logs/log_summary.log', 'logRunning': '/home/mkuntz/twister/logs/log_running.log', 'logCli': '/home/mkuntz/twister/logs/CLI.log', 'logTest': '/home/mkuntz/twister/logs/log_test.log', 'logDebug': '/home/mkuntz/twister/logs/log_debug.log'}`!

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify fix provided on 23rd August load

**Comment by mtkuntz** [comment]
fixed in V2:022 OK to Close
