### ISSUE TITLE
plugins description cannot be read, and not functional

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#70]
V2:021

plugins description cannot be read.
![plugin_fail](https://f.cloud.github.com/assets/4291929/995003/cf7af72e-09b5-11e3-8c4c-11eb21599c15.jpg)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
This is ready for verification, fix delivered on 6th September

**Comment by mtkuntz** [comment]
Cleared out cache .twister and moved further along but cannot create Snapshot..
![plug](https://f.cloud.github.com/assets/4291929/1114897/1b71d5cc-1a22-11e3-9d5e-a0e4d4be978f.jpg)

**Comment by mtkuntz** [comment]
No change with V.::025. Same error message.

**Comment by mtkuntz** [comment]
Fixed "name" as requested
was
 <Plugin>
                <name>GIT</name>
                <jarfile>GITPlugin.jar</jarfile>
                <pyfile>GITPlugin.py</pyfile>
                <status>enabled</status>
                <property>

now

 <Plugin>
                <name>GITPlugin</name>
                <jarfile>GITPlugin.jar</jarfile>
                <pyfile>GITPlugin.py</pyfile>
                <status>enabled</status>
                <property>

not sure when the .xml file got changed.
Please fix spelling of "snapshot", in gui and popup.

**Comment by mtkuntz** [comment]
OK to Close
