### ISSUE TITLE
email warnings misplaced, could be more specific

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#71]
In the Email configuration I have no Subject line, and no Message. I can save it this way. No warnings are posted.

When I login or Save the Paths, I get warnings referring to the "framework config".

![subject_tag](https://f.cloud.github.com/assets/4291929/997220/a0d88940-09dd-11e3-94a8-b591c4750655.jpg)
![mesaage_tag](https://f.cloud.github.com/assets/4291929/997221/a34eaaf6-09dd-11e3-9226-9272dd13b452.jpg)

Warning should also post while I am saving the Email config.
Change warning to "Subject line is empty in email config. file."
Change warning to "Message body is empty in email config. file."

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
OK to Close
