### ISSUE TITLE
Project panel becomes empty after Save Configuration

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#72]
Load Project.xml with a Suite and TestCase.
Project frame shows Suite and Test Case. Run the Test Case (passes)

![before](https://f.cloud.github.com/assets/4291929/997503/b1bff094-09e3-11e3-9941-7330f43faa60.jpg)

Go to Config Tab ->Paths
Save Config.
Go back to Project Tab
Project frame is empty.

![after](https://f.cloud.github.com/assets/4291929/997504/b8438232-09e3-11e3-97cb-a32ce84196ba.jpg)

(I can press run and test DOES run). Reloading the Project file does not help. Need to log out, and in,

**Comment by bogdanpopescu** [comment]
@mtkuntz 
If you press Edit it will show you the test cases in project file. No need to logout.

**Comment by bogdanpopescu** [comment]
We will re-init the project tab to show the files included in the project.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify fix provided on 23rd August load

**Comment by mtkuntz** [comment]
OK to Close.
