### ISSUE TITLE
Configured CLI.log filename not being used.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#73]
regardless of my editing, the CLI log file created in the /logs is ALWAYS created as epname_CLI.log.
Example"
if Pearl327-1001 is the EP name then the CLI log will be Pearl327-1001_CLI.log.

Edit the filename to aCLI.log, and the GUI creates a tab called Pearl327-1001_aCLI.log
An error message is displayed, because that file was not created.
![badcli_tab](https://f.cloud.github.com/assets/4291929/997559/b048197e-09e5-11e3-980f-6bc5551ef588.jpg)

Look on the machine in /logs folder and the file used is Pearl327-1001_CLI.log

**Comment by bogdanpopescu** [comment]
The user should have the right to define the file name. This is a bug that needs to be fixed.

**Comment by croqaz** [comment]
Bug was fixed, you should be able to test it in the next update.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify fix provided on 23rd August load

**Comment by mtkuntz** [comment]
Fixed, OK to close.
