### ISSUE TITLE
Test Case Iterations <Feature Request>

### ISSUE THREAD

**Issue by baluthomas** [Luxoft/Twister#74]
A mechanism to run a single test case multiple times should be available.
A check box and a text box should be available when user clicks on the test case by which he can enable iteration and enter no of times the test case should run.

**Comment by popwich** [comment]
shouldn't 'num of run' variable able to do this?

**Comment by bogdanpopescu** [comment]
2 mechanisms are available today:
- using GUI it is possible to specify how many times a test case can be repeated
- using a test configuration file that store an iterator variable
