### ISSUE TITLE
No warning that Suite Option: CE_Type: is not set. Cause database write to fail. 

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#75]
I did not set Suite Option: CE_Type.

CLI log produces.

saveToDatabase: User `mkuntz`, file `/home/mkuntz/twister/demo/testsuite-python/test_py_printnlogs.py`: Cannot build query! Error on `'CE_Type'`!

Similar to having a null Run Numberr; I should get a pop-up warning.

**Comment by bogdanpopescu** [comment]
The warning is printed out if the filed is set as mandatory in db.xml. It is a matter of configuration.
Example from db.xml:
field FieldName="" FromTable="" GUIDefined="true" ID="Run_Number" Label="Run Number:" Mandatory="true" SQLQuery="" Type="UserText"
If mandatory="true" the framework will not start execution if the filed is empty and an error message is printed.

**Comment by mtkuntz** [comment]
My bug report is that there was no Warning in the GUI for null CE_TYPE
Here's the warning for Run Number

![rn_warn](https://f.cloud.github.com/assets/4291929/1021202/3b6286b4-0cea-11e3-9140-31d533dd49af.jpg)

**Comment by mtkuntz** [comment]
OK to Close - CE_type is no longer part of the Suite Options
