### ISSUE TITLE
Database Password is not reloaded correctly when editing.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#76]
Set up Database, Server, User, Password. Save to db.xml. my password will be encrypted in the file.
Log out.
Log in.
Go to Database attributes and change only the Server. Save to db.xml.
The encrypted password was loaded, not my original password. So the act of saving is storing an encrypted version of the encrypted password. And the server login fails.
(workaround is to re-type the password every time)

**Comment by mtkuntz** [comment]
please Close Issue#43, the original request was resolved.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify fix provided on 23rd August load

**Comment by mtkuntz** [comment]
OK to close.
