### ISSUE TITLE
Email not working, CLI logs exceptions and internal command failure trying to kill Log Server.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#77]
Email from server is not working
sendMail: E-mail: Sending e-mail exception `list index out of range` !
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
setExecStatus: Cannot stop Log Server PID `6170`, for user `mkuntz`! Exception `[Errno 3] No such process`!

(we run csh, set by IT department, not bash)

**Comment by bogdanpopescu** [comment]
That is because of the csh shell. We'll investigate.

**Comment by croqaz** [comment]
Fixed the LogServer. Instead of killing it, we are asking it nicely to stop.
This should work no matter what kind of shell you use.
The change will be available in the next commit.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
Works now - OK to close
