### ISSUE TITLE
Request Error message if user/twister not installed

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#78]
Please change the Warning in case a user has not had a client installation to an Error with a better description.
The text that the CE is not running is incorrect.
![no_client](https://f.cloud.github.com/assets/4291929/1016672/5067dba4-0bff-11e3-9381-814b4c99ef20.jpg)

(I simply removed my /twister folder to cause this)

suggested correction
Error
 ! Client has not been installed, please install latest Client package.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
OK to close
![no_client_msg](https://f.cloud.github.com/assets/4291929/1084256/39123e72-15aa-11e3-8154-b1cf036613bd.jpg)
