### ISSUE TITLE
PanicDetect is not fully functional

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#79]
using V.:2.022
1. Panic Detected is enabled on the Suite Option. Panic detect is disregarding the flag on an individual Regex, and is always searching the log for all Regex entries.
2. The status on the Test that was trapped is "running". The test status should be stopped.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
Works now. Results is the same as if I had hit STOP. OK to Close.
