### ISSUE TITLE
Global param checked "Stop on fail" not working; also not saved like other GP's

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#80]
My results are the same whether Global "Stop on fail" is checked or not. I Save Project every time I change the settings.
The 3rd test is returns fail, it is not optional. 
The user guide says "   Stop on fail = if a test that is mandatory will fail, or will crash, all the project will fail ;"

![st_on_f](https://f.cloud.github.com/assets/4291929/1021232/76ace832-0cee-11e3-84e4-849eb4aed592.jpg)

Second problem is that I return to Edit, then Stop on fail is no longer checked. I should not have to check it again.
![st_on_f_post](https://f.cloud.github.com/assets/4291929/1021238/c5c1e27e-0cee-11e3-82f7-cc31d49448e8.jpg)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
Working now. OK to Close.
![st_on_f_post_new](https://f.cloud.github.com/assets/4291929/1089887/46d40f3e-164c-11e3-9664-3dc8e7489c0a.jpg)
