### ISSUE TITLE
Library selection and de-selection not behaving as expected

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#81]
The selection and subsequent behavior is not correct.

Case 1:
Selected “none” in both Global and Suite:

downloadLibrary: CE: Requested library file: `TscCommonLib.py`.
downloadLibrary: CE: Requested library folder: `Ixia`.
downloadLibrary: CE: Requested library file: `TscFtpLib.py`.
downloadLibrary: CE: Requested library file: `TscSshLib.py`.
downloadLibrary: CE: Requested library file: `TscStepLib.py`.
downloadLibrary: CE: Requested library file: `TscTelnetLib.py`.
downloadLibrary: CE: Requested library file: `TscTestBedLib.py`.
downloadLibrary: CE: Requested library file: `TscThreadsLib.py`.
downloadLibrary: CE: Requested library file: `TscUnitTestLib.py`.

desired behavior : No libs get downloaded.

Case 2:
Selected “all” in both Global and Suite:

downloadLibrary: CE: Requested library file: `TscCommonLib.py`.
downloadLibrary: CE: Requested library folder: `Ixia`.
downloadLibrary: CE: Requested library file: `TscFtpLib.py`.
downloadLibrary: CE: Requested library file: `TscSshLib.py`.
downloadLibrary: CE: Requested library file: `TscStepLib.py`.
downloadLibrary: CE: Requested library file: `TscTelnetLib.py`.
downloadLibrary: CE: Requested library file: `TscTestBedLib.py`.
downloadLibrary: CE: Requested library file: `TscThreadsLib.py`.
downloadLibrary: CE: Requested library file: `TscUnitTestLib.py`.
echo: Echo: TestBed: Checking connection...
echo: Echo: ping
downloadLibrary: CE: Requested library file: `TscCommonLib.py`. //second time
downloadLibrary: CE: Requested library folder: `Ixia`. //second time

desired behavior : All libs get downloaded, none twice

Case 3
In Globals I selected TscThreadsLib.py
In Suite I selected just TscUnitTestLib.py

downloadLibrary: CE: Requested library file: `TscCommonLib.py`. //should not 
downloadLibrary: CE: Requested library file: `TscThreadsLib.py`.
echo: Echo: ping
downloadLibrary: CE: Requested library file: `TscCommonLib.py`. //should not
downloadLibrary: CE: Requested library file: `TscUnitTestLib.py`.

desired behavior : selected libs get downloaded

**Comment by croqaz** [comment]
Case 1: implemented. By default, only the mandatory library `TscCommonLib` will be downloaded, instead of all libraries.
Case 2: implemented. Any library will be checked to download just ONE TIME.
Case 3: In Globals you select TscThreadsLib.py, in Suite you select TscUnitTestLib.py ::
The runner will download TscCommonLib.py + TscThreadsLib.py, then when the suite begins, it will download TscUnitTestLib.py.

This will be available in the next commit.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
OK to Close
