### ISSUE TITLE
User Guide 8 - "How to run the test files" missing Icon for Timeout

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#82]
8 - "How to run the test files" missing Icon for Timeout

![st_on_f](https://f.cloud.github.com/assets/4291929/1021321/3315e526-0cf6-11e3-8df6-398201f9ec7f.jpg)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by mtkuntz** [comment]
not Fixed - page 28 of the Sept. 2 version.

**Comment by mtkuntz** [comment]
OK to Close - fixed in Sept. 10th version
![icons](https://f.cloud.github.com/assets/4291929/1114942/c35917d2-1a22-11e3-8dcf-b7b57014254f.jpg)
