### ISSUE TITLE
Stop button does not clean-up test status.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#84]
The user manual is not too clear on this
"...If the Run button is enabled, you can start the execution. At the same time, the Stop button will activate, to allow stopping the Central Engine and killing all the running processes and the Run button will become Pause, allowing to pause after the current tests finishes its execution."

Queued 3 tests, hit Run
Hit Stop before third test finishes.
Run button comes back.
3rd test should show Stopped, not running. should be counted in summary as Stopped.

![not_stopped](https://f.cloud.github.com/assets/4291929/1021406/8e2416e2-0cfe-11e3-8fdb-aee0daa029e6.jpg)

Is the intention show the user the last status before the processes were killed?

"...If the Run button is enabled, you can start the execution. The Run button will become Pause, allowing you to pause after the current tests finishes its execution. Use Resume to continue the execution.
When execution is underway, the Stop button will activate, to allow stopping the Central Engine and killing all the running processes. Test status will freeze to show the last status."

**Comment by croqaz** [comment]
Updated the documentation to be more clear:

If the Run button is disabled, it means that the Central Engine service is not running, so the execution cannot start.
If the Run button is enabled, you can start the execution. When you start the execution, the Stop button will activate, to allow stopping the Central Engine and killing all the running processes and the Run button will become Pause, allowing to pause after the current tests finishes its execution.

If the Central Engine was started recently, by default all the files will be in state pending .
If a previous run was completed, the most recent status is displayed (pass, failed, etc.).

If the execution is stopped prematurely, all files that did not execute (files in pending), have status NOT EXECUTED.

This will appear in the next commit.

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Please verify

**Comment by sandhyamisra** [comment]
This still doesn't seem to work. Tested with 30.08.2013 build
![capture](https://f.cloud.github.com/assets/4291567/1067445/d9e253f0-13cf-11e3-90b9-74c47191da5a.JPG)

**Comment by mtkuntz** [comment]
OK to Close - its a matter of timing.

![stop](https://f.cloud.github.com/assets/4291929/1115203/1eb26382-1a27-11e3-8efe-19f7eb3562a5.jpg)
