### ISSUE TITLE
Twister server upgrade fails

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#86]
While doing an upgrade on an existing installation, the server installation fails with the following error message:

[choffman@pearl326 installer]$ sudo python2.7 installer.py

Please select what you wish to install:
[1] the Twister dependencies (must be ROOT)
[2] the Twister clients
[3] the Twister servers
[q] e[x]it, don't install anything
Your choice: 3
Will install servers.

Welcome to the Twister Installer !

Please type where you wish to install the servers.
Don't forget to add `twister` at the end of the path!
Leave EMPTY to install in default path `/opt/twister`:
Path :

WARNING! Another version of Twister is installed at `/opt/twister/`!
If you continue, all files from that folder will be PERMANENTLY DELETED!!
If you created custom libs (in lib/ folder) and plugins (in plugin/ folder),
you should make a back-up, then restart the installer.
Are you sure you want to continue? (yes/no): yes

Back-up `config` folder (from `/opt/twister/config` to `/home/choffman/twister_2                                              3_August/installer`)...
Traceback (most recent call last):
  File "installer.py", line 67, in <module>
    import installer_server
  File "/home/choffman/twister_23_August/installer/installer_server.py", line 93                                              , in <module>
    shutil.move(INSTALL_PATH + 'config', os.getcwd())
  File "/usr/local/lib/python2.7/shutil.py", line 298, in move
    copytree(src, real_dst, symlinks=True)
  File "/usr/local/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/local/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/choffman/twister_23_August/install                                              er/config'
[choffman@pearl326 installer]$

**Comment by croqaz** [comment]
Hello,
Because the installer_server runs as root, it cannot write in your home folder, which is a NIS mount.
Problem fixed, you will see the fix in the next commit.

**Comment by bogdanpopescu** [comment]
@CJHoffmann 
Please verify

**Comment by CJHoffmann** [comment]
Server upgrade now works as expected.
