### ISSUE TITLE
Need to login twice to get to the test execution page

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#87]
When you open a new browser session and login to twister and try to click on test execution logo, it goes back to the login page. 

Browser used: Mozilla firefox 
Twister Version:  2.022 (23rd Aug)

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
Please enable Java console and send the console log when the issue is happening.

**Comment by sandhyamisra** [comment]
Sent the console log to Bogdan via email. Even with 30th august build user is sometimes redirected to the login page (happens randomly)

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
Can you check what is the timeout value for your user ?

**Comment by sandhyamisra** [comment]
Timeout is set to 15... but I don't think I have left twister idle for more than a minute.

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
Hi, do you have the same issue ? We cannot reproduce it here.

**Comment by sandhyamisra** [comment]
We still see this issue with 0913 load

**Comment by sandhyamisra** [comment]
This issues seems to be resolved with 1028 load. Can be closed.
