### ISSUE TITLE
Enhancement: Provide file_attributes when browsing a directory.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#9]
Version: V.:2.001
Not all dialog boxes provide a "details" button, details are helpful when selecting files.

Works from Browse: Select XML File dialog from the Configuration:Database tab.
But from "..." Configuration:Paths "EP name File", the details button is missing.
Similarly from the Project File Tab - open Project File dialog shows only file_names.

**Comment by bogdanpopescu** [comment]
Provided fix in tag 31_05_2013.
@mtkuntz please verify it.

**Comment by mtkuntz** [comment]
V: 2.003 seems to have broken things
I try opening the dialog box ... and IE just hangs

**Comment by sandhyamisra** [comment]
Partly resolved.

The file details are visible for Configuration Tab EP name path open file dialog
The open project dialog box still doesn't have the file details, only the file names are listed.
![file-attributes-open-projectdialog](https://f.cloud.github.com/assets/4291567/761129/c574193a-e7c4-11e2-83b4-c2df4c2c16f8.JPG)
![fileattrib-config-eptab](https://f.cloud.github.com/assets/4291567/761130/c578da92-e7c4-11e2-9d05-2ccc1ce188a7.JPG)

**Comment by mtkuntz** [comment]
OK to Close
