### ISSUE TITLE
Add User takes 8 minutes in large NIS community.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#90]
Add User takes 8 minutes in large NIS community.
Its NFS/NIS again. Please add a text-entry for a single userid and then using a ypmatch request, instead of ypcat. - Mike

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 6th September. Please verify it.

**Comment by mtkuntz** [comment]
Works! OK to Close.
