### ISSUE TITLE
Twister 2.023 not loading secondary libraries

### ISSUE THREAD

**Issue by JimCamp** [Luxoft/Twister#91]
The Aug 30 Twister load does not load the secondary libraries needed for our scripts to run. The directory location for the libs is specified in the paths config

**Comment by mtkuntz** [comment]
This seems to happen if I have at least one lib loaded from Global Options. If I have no libs selected in Global Options, then my own libs loaded OK.

**Comment by bogdanpopescu** [comment]
@JimCamp 
Fix delivered on Friday 6th September. Please verify.

**Comment by mtkuntz** [comment]
Wes requested in Issue #81 that the GUI selection match behavior. That was resolved.This fix allows the user to select secondary libraries at the same time as twister libs. That works as well. This Issue is OK to close.

**Comment by JimCamp** [comment]
By default I think that all libraries should be selected in gui, as many will be needed to run tests.
