### ISSUE TITLE
Twister client upgrade fails

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#92]
A common install directory is often used to store and run the twister install scripts.
This could be an administrators directory or in /opt.  The permissions of the install directory do not allow non-root users to run the client install script from these directories and upgrade their clients.  It seems this is because the user's config directory is first backed up in the directory where the install script resides.  Permissions do not allow the creation of that directory.

Maybe the backup config directory can be stored in the ~/.twister directory?

**Comment by croqaz** [comment]
Changed the backup mechanism:
If the user is ROOT, the backup of config files will be done in `/tmp/twister_server_config`, where the ROOT can write.
If the user is normal, will now backup in `~/.twister`, where the user can write.
This should fix the problem permanently.
The change will land in the next release.

**Comment by CJHoffmann** [comment]
Installations from a user's directory or administrator's are both successful.  Using 131004 package
