### ISSUE TITLE
Cannot ctrl-C (copy) from TestBed or SUT and paste to TestConfig

### ISSUE THREAD

**Issue by CJHoffmann** [Luxoft/Twister#93]
Want to copy a TB or SUT id or path value and paste to a test config parameter.
There does not seem to be any way to copy a id or path value from the TB or SUT window.  Tried using cntrl-C (the typical copy keyboard shortcut).

Then, going to the TestConfiguration window, selecting the parameter value where I want to put the string and using cntrl-V (the typical paste keyboard shortcut) either nothing is pasted or a string from an earlier copy is pasted.

I get similar results if I try and copy from the TB or SUT windows and try and paste it into a text editor (i.e. notepad). That is, nothing from the TB or SUT window is copied.

**Comment by croqaz** [comment]
This is work in progress, will probably be available after the next week.

**Comment by CJHoffmann** [comment]
For the original scenario described, the ctrl-C will copy a highlighted string from a TB or SUT and ctrl-V will past the value in a configuration component.
