### ISSUE TITLE
cli.py options don't work

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#97]
> > cli.py --users

Hello, user `user1`.

Cannot connect to Central Engine server! Error `<ProtocolError for user:password@127.0.0.1:8000/: 401 Unauthorized>` ! Exiting!

same results with --eps, --stats, --details, --status-details,

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
You must specify the Twister server and the credentails to have the command working.
./cli.py --users --server http://<username>:<user_password>@<server>:8000/

**Comment by sandhyamisra** [comment]
Thanks it works
