### ISSUE TITLE
Some log entries in server_log.log do not contain time stamps

### ISSUE THREAD

**Issue by toma010** [Luxoft/Twister#98]
_logConnect: Sock connect exception: `[Errno 111] Connection refused`.
_logConnect: Internal Log Error! Could not connect to Log Server!
_logServerMsg: Creating a new connection...
_logServer: Log Server for user `daffy` launched on `127.0.0.1:61489` - PID `12304`.
_logConnect: Sock connect exception: `[Errno 111] Connection refused`.
_logConnect: Internal Log Error! Could not connect to Log Server!
Log: Preparing to start on `61489`...
Log: Started server on `('0.0.0.0', 61489)`.

**Comment by croqaz** [comment]
Hello,
This information is from the Log Server, not from the Central Engine.
I have redirected the output in the log_srv.log exclusively, so you won't see the print again.
This is be available in the version from 12.dec.2013.
~ Cristi

**Comment by toma010** [comment]
As the title stated this wasn’t about any specific message or it’s origin. The bug was that many of the messages in the log are not time stamped.

Attached is a log were very few messages have time stamps.

Thanks

Tom

**Comment by mtkuntz** [comment]
Ok to Close - fixed
