### ISSUE TITLE
Return Invalid shows Timeout, not Invalid.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#99]
in my test program I force 

error_code = "INVALID"
return error_code

shows timeout in the GUI.

**Comment by bogdanpopescu** [comment]
Fix provided

**Comment by mtkuntz** [comment]
Works now. (.040) OK to close

**Comment by bogdanpopescu** [comment]
An issue was spotted in GUI. Re-openning.

**Comment by mtkuntz** [comment]
Software is OK, User manual does not show Invalid, but we can close this Issue.
